function sc_initialize_menu_topscores() {
	selected_leaderboard = 0;
	selected_column = 0;
	
	upgrade_name[0] = "UNUSED";
	upgrade_name[4] = "Missiles";
	upgrade_name[6] = "Dual Shot";
	upgrade_name[8] = "Triple Shot";
	upgrade_name[10] = "Quad Shot";
	upgrade_name[12] = "Dual Missiles";
	upgrade_name[14] = "Triple Missiles";
	upgrade_name[20] = "Laser";
	upgrade_name[22] = "Shield";
	upgrade_name[24] = "Drone Ship";
	upgrade_name[26] = "Bullet Speed";
	upgrade_name[28] = "Hull Upgrade";
	upgrade_name[30] = "Speed";
	upgrade_name[32] = "Shooting Speed";
	upgrade_name[34] = "Rammer";
	upgrade_name[36] = "Flak Speed";
	upgrade_name[38] = "Flak";
	upgrade_name[40] = "Drone Hardware";
	upgrade_name[48] = "Missile Defense";
	upgrade_name[50] = "Turn Speed";
	upgrade_name[54] = "Plated Missiles";
	upgrade_name[56] = "Missile Tracking";
	upgrade_name[58] = "Drone Construction";
	upgrade_name[60] = "Ion Cannon";
	upgrade_name[62] = "Ion Recharge";
	upgrade_name[64] = "Cloaking Device";
	upgrade_name[66] = "Cloak Recharge";
	upgrade_name[68] = "Cloak Length";
	upgrade_name[70] = "Shield Strength";
	upgrade_name[72] = "Shield Regen";
	upgrade_name[74] = "Missile Reload";
	upgrade_name[76] = "Gun Cooldown";
	upgrade_name[78] = "Acceleration";
	upgrade_name[80] = "Single Shot";
	upgrade_name[82] = "Max Drones";
	upgrade_name[82] = "Missile Turret";
	upgrade_name[84] = "Missile Turret Cooldown";
	upgrade_name[86] = "Missile Turret Turn Speed";
	upgrade_name[88] = "Gun Turret";
	upgrade_name[90] = "Turret Cooldown";
	upgrade_name[92] = "Turret Turn Speed";
	upgrade_name[96] = "Health";
	upgrade_name[98] = "Healer Nanites";

}