function sc_draw_menu_stats(start_x, start_y) {
	if sel_menu = 9 { //stats
		start_y += 64;
		var _add_y = 0;
		var _add_x = 0;
		
		draw_set_halign(fa_middle);
		draw_text(start_x + 1536/2, start_y + stats_adjust_y - 64, "Stats");
		draw_set_halign(fa_left);
		
		draw_text(start_x + _add_x, start_y + stats_adjust_y + _add_y, "record_points"); _add_x += 1536	draw_text(start_x + _add_x, start_y + stats_adjust_y + _add_y, steam_get_stat_int("record_points")); _add_y += 64; _add_x = 0;
		draw_text(start_x + _add_x, start_y + stats_adjust_y + _add_y, "highest_wave"); _add_x += 1536	draw_text(start_x + _add_x, start_y + stats_adjust_y + _add_y, steam_get_stat_int("highest_wave")); _add_y += 64; _add_x = 0;
		draw_text(start_x + _add_x, start_y + stats_adjust_y + _add_y, "total_kills"); _add_x += 1536;	draw_text(start_x + _add_x, start_y + stats_adjust_y + _add_y, steam_get_stat_int("total_kills")); _add_y += 64; _add_x = 0;
		draw_text(start_x + _add_x, start_y + stats_adjust_y + _add_y, "total_rounds"); _add_x += 1536;	draw_text(start_x + _add_x, start_y + stats_adjust_y + _add_y, steam_get_stat_int("total_rounds")); _add_y += 64; _add_x = 0;
		draw_text(start_x + _add_x, start_y + stats_adjust_y + _add_y, "total_deaths"); _add_x += 1536;	draw_text(start_x + _add_x, start_y + stats_adjust_y + _add_y, steam_get_stat_int("total_deaths")); _add_y += 64; _add_x = 0;
		draw_text(start_x + _add_x, start_y + stats_adjust_y + _add_y, "total_upgrades"); _add_x += 1536;	draw_text(start_x + _add_x, start_y + stats_adjust_y + _add_y, steam_get_stat_int("total_upgrades")); _add_y += 64; _add_x = 0;
		draw_text(start_x + _add_x, start_y + stats_adjust_y + _add_y, "total_hitby"); _add_x += 1536;	draw_text(start_x + _add_x, start_y + stats_adjust_y + _add_y, steam_get_stat_int("total_hitby")); _add_y += 64; _add_x = 0;
		draw_text(start_x + _add_x, start_y + stats_adjust_y + _add_y, "total_shotby"); _add_x += 1536;	draw_text(start_x + _add_x, start_y + stats_adjust_y + _add_y, steam_get_stat_int("total_shotby")); _add_y += 64; _add_x = 0;
		draw_text(start_x + _add_x, start_y + stats_adjust_y + _add_y, "total_enemy_shields_destroyed"); _add_x += 1536	draw_text(start_x + _add_x, start_y + stats_adjust_y + _add_y, steam_get_stat_int("total_enemy_shields_destroyed")); _add_y += 64; _add_x = 0;
		
		draw_text(start_x + _add_x, start_y + stats_adjust_y + _add_y, "kills_basic"); _add_x += 1536;	draw_text(start_x + _add_x, start_y + stats_adjust_y + _add_y, steam_get_stat_int("kills_basic")); _add_y += 64; _add_x = 0;
		draw_text(start_x + _add_x, start_y + stats_adjust_y + _add_y, "kills_suicider"); _add_x += 1536;	draw_text(start_x + _add_x, start_y + stats_adjust_y + _add_y, steam_get_stat_int("kills_suicider")); _add_y += 64; _add_x = 0;
		draw_text(start_x + _add_x, start_y + stats_adjust_y + _add_y, "kills_marauder"); _add_x += 1536;	draw_text(start_x + _add_x, start_y + stats_adjust_y + _add_y, steam_get_stat_int("kills_marauder")); _add_y += 64; _add_x = 0;
		draw_text(start_x + _add_x, start_y + stats_adjust_y + _add_y, "kills_ion"); _add_x += 1536;	draw_text(start_x + _add_x, start_y + stats_adjust_y + _add_y, steam_get_stat_int("kills_ion")); _add_y += 64; _add_x = 0;
		draw_text(start_x + _add_x, start_y + stats_adjust_y + _add_y, "kills_bomber"); _add_x += 1536;	draw_text(start_x + _add_x, start_y + stats_adjust_y + _add_y, steam_get_stat_int("kills_bomber")); _add_y += 64; _add_x = 0;
		draw_text(start_x + _add_x, start_y + stats_adjust_y + _add_y, "kills_rusher"); _add_x += 1536;	draw_text(start_x + _add_x, start_y + stats_adjust_y + _add_y, steam_get_stat_int("kills_rusher")); _add_y += 64; _add_x = 0;
		draw_text(start_x + _add_x, start_y + stats_adjust_y + _add_y, "kills_sniper"); _add_x += 1536;	draw_text(start_x + _add_x, start_y + stats_adjust_y + _add_y, steam_get_stat_int("kills_sniper")); _add_y += 64; _add_x = 0;
		draw_text(start_x + _add_x, start_y + stats_adjust_y + _add_y, "kills_gunship"); _add_x += 1536;	draw_text(start_x + _add_x, start_y + stats_adjust_y + _add_y, steam_get_stat_int("kills_gunship")); _add_y += 64; _add_x = 0;
		draw_text(start_x + _add_x, start_y + stats_adjust_y + _add_y, "kills_shotgunner"); _add_x += 1536;	draw_text(start_x + _add_x, start_y + stats_adjust_y + _add_y, steam_get_stat_int("kills_shotgunner")); _add_y += 64; _add_x = 0;
		draw_text(start_x + _add_x, start_y + stats_adjust_y + _add_y, "kills_destroyer"); _add_x += 1536;	draw_text(start_x + _add_x, start_y + stats_adjust_y + _add_y, steam_get_stat_int("kills_destroyer")); _add_y += 64; _add_x = 0;
		draw_text(start_x + _add_x, start_y + stats_adjust_y + _add_y, "kills_swarmer"); _add_x += 1536;	draw_text(start_x + _add_x, start_y + stats_adjust_y + _add_y, steam_get_stat_int("kills_swarmer")); _add_y += 64; _add_x = 0;
		draw_text(start_x + _add_x, start_y + stats_adjust_y + _add_y, "kills_heavy_cruiser"); _add_x += 1536;	draw_text(start_x + _add_x, start_y + stats_adjust_y + _add_y, steam_get_stat_int("kills_heavy_cruiser")); _add_y += 64; _add_x = 0;
		draw_text(start_x + _add_x, start_y + stats_adjust_y + _add_y, "kills_battlecruiser"); _add_x += 1536;	draw_text(start_x + _add_x, start_y + stats_adjust_y + _add_y, steam_get_stat_int("kills_battlecruiser")); _add_y += 64; _add_x = 0;
		draw_text(start_x + _add_x, start_y + stats_adjust_y + _add_y, "kills_turret_large"); _add_x += 1536;	draw_text(start_x + _add_x, start_y + stats_adjust_y + _add_y, steam_get_stat_int("kills_turret_large")); _add_y += 64; _add_x = 0;
		draw_text(start_x + _add_x, start_y + stats_adjust_y + _add_y, "kills_turret_laser"); _add_x += 1536;	draw_text(start_x + _add_x, start_y + stats_adjust_y + _add_y, steam_get_stat_int("kills_turret_laser")); _add_y += 64; _add_x = 0;
		draw_text(start_x + _add_x, start_y + stats_adjust_y + _add_y, "kills_turret_missile"); _add_x += 1536;	draw_text(start_x + _add_x, start_y + stats_adjust_y + _add_y, steam_get_stat_int("kills_turret_missile")); _add_y += 64; _add_x = 0;
		draw_text(start_x + _add_x, start_y + stats_adjust_y + _add_y, "kills_turret_ion"); _add_x += 1536;	draw_text(start_x + _add_x, start_y + stats_adjust_y + _add_y, steam_get_stat_int("kills_turret_ion")); _add_y += 64; _add_x = 0;
		draw_text(start_x + _add_x, start_y + stats_adjust_y + _add_y, "kills_station_hatch"); _add_x += 1536	draw_text(start_x + _add_x, start_y + stats_adjust_y + _add_y, steam_get_stat_int("kills_station_hatch")); _add_y += 64; _add_x = 0;
		draw_text(start_x + _add_x, start_y + stats_adjust_y + _add_y, "kills_station_rocket_launcher"); _add_x += 1536	draw_text(start_x + _add_x, start_y + stats_adjust_y + _add_y, steam_get_stat_int("kills_station_rocket_launcher")); _add_y += 64; _add_x = 0;
		draw_text(start_x + _add_x, start_y + stats_adjust_y + _add_y, "kills_station_hanger"); _add_x += 1536	draw_text(start_x + _add_x, start_y + stats_adjust_y + _add_y, steam_get_stat_int("kills_station_hanger")); _add_y += 64; _add_x = 0;
		draw_text(start_x + _add_x, start_y + stats_adjust_y + _add_y, "kills_station_shield"); _add_x += 1536	draw_text(start_x + _add_x, start_y + stats_adjust_y + _add_y, steam_get_stat_int("kills_station_shield")); _add_y += 64; _add_x = 0;
		draw_text(start_x + _add_x, start_y + stats_adjust_y + _add_y, "kills_station_core"); _add_x += 1536	draw_text(start_x + _add_x, start_y + stats_adjust_y + _add_y, steam_get_stat_int("kills_station_core")); _add_y += 64; _add_x = 0;
		draw_text(start_x + _add_x, start_y + stats_adjust_y + _add_y, "kills_turret_station"); _add_x += 1536	draw_text(start_x + _add_x, start_y + stats_adjust_y + _add_y, steam_get_stat_int("kills_turret_station")); _add_y += 64; _add_x = 0;
		draw_text(start_x + _add_x, start_y + stats_adjust_y + _add_y, "kills_turret_station_double"); _add_x += 1536	draw_text(start_x + _add_x, start_y + stats_adjust_y + _add_y, steam_get_stat_int("kills_turret_station_double")); _add_y += 64; _add_x = 0;


		
		draw_text(start_x + _add_x, start_y + stats_adjust_y + _add_y, "total_hitby"); _add_x += 1536;	draw_text(start_x + _add_x, start_y + stats_adjust_y + _add_y, steam_get_stat_int("total_hitby")); _add_y += 64; _add_x = 0;
		draw_text(start_x + _add_x, start_y + stats_adjust_y + _add_y, "hitby_basic"); _add_x += 1536;	draw_text(start_x + _add_x, start_y + stats_adjust_y + _add_y, steam_get_stat_int("hitby_basic")); _add_y += 64; _add_x = 0;
		draw_text(start_x + _add_x, start_y + stats_adjust_y + _add_y, "hitby_suicider"); _add_x += 1536;	draw_text(start_x + _add_x, start_y + stats_adjust_y + _add_y, steam_get_stat_int("hitby_suicider")); _add_y += 64; _add_x = 0;
		draw_text(start_x + _add_x, start_y + stats_adjust_y + _add_y, "hitby_marauder"); _add_x += 1536;	draw_text(start_x + _add_x, start_y + stats_adjust_y + _add_y, steam_get_stat_int("hitby_marauder")); _add_y += 64; _add_x = 0;
		draw_text(start_x + _add_x, start_y + stats_adjust_y + _add_y, "hitby_ion"); _add_x += 1536;	draw_text(start_x + _add_x, start_y + stats_adjust_y + _add_y, steam_get_stat_int("hitby_ion")); _add_y += 64; _add_x = 0;
		draw_text(start_x + _add_x, start_y + stats_adjust_y + _add_y, "hitby_bomber"); _add_x += 1536;	draw_text(start_x + _add_x, start_y + stats_adjust_y + _add_y, steam_get_stat_int("hitby_bomber")); _add_y += 64; _add_x = 0;
		draw_text(start_x + _add_x, start_y + stats_adjust_y + _add_y, "hitby_rusher"); _add_x += 1536;	draw_text(start_x + _add_x, start_y + stats_adjust_y + _add_y, steam_get_stat_int("hitby_rusher")); _add_y += 64; _add_x = 0;
		draw_text(start_x + _add_x, start_y + stats_adjust_y + _add_y, "hitby_ranger"); _add_x += 1536;	draw_text(start_x + _add_x, start_y + stats_adjust_y + _add_y, steam_get_stat_int("hitby_ranger")); _add_y += 64; _add_x = 0;
		draw_text(start_x + _add_x, start_y + stats_adjust_y + _add_y, "hitby_gunship"); _add_x += 1536;	draw_text(start_x + _add_x, start_y + stats_adjust_y + _add_y, steam_get_stat_int("hitby_gunship")); _add_y += 64; _add_x = 0;
		draw_text(start_x + _add_x, start_y + stats_adjust_y + _add_y, "hitby_shotgunner"); _add_x += 1536;	draw_text(start_x + _add_x, start_y + stats_adjust_y + _add_y, steam_get_stat_int("hitby_shotgunner")); _add_y += 64; _add_x = 0;
		draw_text(start_x + _add_x, start_y + stats_adjust_y + _add_y, "hitby_destroyer"); _add_x += 1536;	draw_text(start_x + _add_x, start_y + stats_adjust_y + _add_y, steam_get_stat_int("hitby_destroyer")); _add_y += 64; _add_x = 0;
		draw_text(start_x + _add_x, start_y + stats_adjust_y + _add_y, "hitby_swarmer"); _add_x += 1536;	draw_text(start_x + _add_x, start_y + stats_adjust_y + _add_y, steam_get_stat_int("hitby_swarmer")); _add_y += 64; _add_x = 0;
		draw_text(start_x + _add_x, start_y + stats_adjust_y + _add_y, "hitby_heavy_cruiser"); _add_x += 1536;	draw_text(start_x + _add_x, start_y + stats_adjust_y + _add_y, steam_get_stat_int("hitby_heavy_cruiser")); _add_y += 64; _add_x = 0;
		draw_text(start_x + _add_x, start_y + stats_adjust_y + _add_y, "hitby_battlecruiser"); _add_x += 1536;	draw_text(start_x + _add_x, start_y + stats_adjust_y + _add_y, steam_get_stat_int("hitby_battlecruiser")); _add_y += 64; _add_x = 0;
		draw_text(start_x + _add_x, start_y + stats_adjust_y + _add_y, "hitby_asteroid"); _add_x += 1536;	draw_text(start_x + _add_x, start_y + stats_adjust_y + _add_y, steam_get_stat_int("hitby_asteroid")); _add_y += 64; _add_x = 0;
		
		draw_text(start_x + _add_x, start_y + stats_adjust_y + _add_y, "total_shotby"); _add_x += 1536;	draw_text(start_x + _add_x, start_y + stats_adjust_y + _add_y, steam_get_stat_int("total_shotby")); _add_y += 64; _add_x = 0;
		draw_text(start_x + _add_x, start_y + stats_adjust_y + _add_y, "total_shotby_ion"); _add_x += 1536;	draw_text(start_x + _add_x, start_y + stats_adjust_y + _add_y, steam_get_stat_int("total_shotby_ion")); _add_y += 64; _add_x = 0;
		draw_text(start_x + _add_x, start_y + stats_adjust_y + _add_y, "total_shotby_laser"); _add_x += 1536;	draw_text(start_x + _add_x, start_y + stats_adjust_y + _add_y, steam_get_stat_int("total_shotby_laser")); _add_y += 64; _add_x = 0;
		draw_text(start_x + _add_x, start_y + stats_adjust_y + _add_y, "total_shotby_missile"); _add_x += 1536;	draw_text(start_x + _add_x, start_y + stats_adjust_y + _add_y, steam_get_stat_int("total_shotby_missile")); _add_y += 64; _add_x = 0;
		draw_text(start_x + _add_x, start_y + stats_adjust_y + _add_y, "total_shotby_bullet"); _add_x += 1536;	draw_text(start_x + _add_x, start_y + stats_adjust_y + _add_y, steam_get_stat_int("total_shotby_bullet")); _add_y += 64; _add_x = 0;
		draw_text(start_x + _add_x, start_y + stats_adjust_y + _add_y, "total_shotby_sniper"); _add_x += 1536;	draw_text(start_x + _add_x, start_y + stats_adjust_y + _add_y, steam_get_stat_int("total_shotby_sniper")); _add_y += 64; _add_x = 0;
		draw_text(start_x + _add_x, start_y + stats_adjust_y + _add_y, "total_shotby_station_bullet"); _add_x += 1536	draw_text(start_x + _add_x, start_y + stats_adjust_y + _add_y, steam_get_stat_int("total_shotby_station_bullet")); _add_y += 64; _add_x = 0;
		draw_text(start_x + _add_x, start_y + stats_adjust_y + _add_y, "shotby_basic"); _add_x += 1536;	draw_text(start_x + _add_x, start_y + stats_adjust_y + _add_y, steam_get_stat_int("shotby_basic")); _add_y += 64; _add_x = 0;
		draw_text(start_x + _add_x, start_y + stats_adjust_y + _add_y, "shotby_suicider"); _add_x += 1536;	draw_text(start_x + _add_x, start_y + stats_adjust_y + _add_y, steam_get_stat_int("shotby_suicider")); _add_y += 64; _add_x = 0;
		draw_text(start_x + _add_x, start_y + stats_adjust_y + _add_y, "shotby_marauder"); _add_x += 1536;	draw_text(start_x + _add_x, start_y + stats_adjust_y + _add_y, steam_get_stat_int("shotby_marauder")); _add_y += 64; _add_x = 0;
		draw_text(start_x + _add_x, start_y + stats_adjust_y + _add_y, "shotby_ion"); _add_x += 1536;	draw_text(start_x + _add_x, start_y + stats_adjust_y + _add_y, steam_get_stat_int("shotby_ion")); _add_y += 64; _add_x = 0;
		draw_text(start_x + _add_x, start_y + stats_adjust_y + _add_y, "shotby_bomber"); _add_x += 1536;	draw_text(start_x + _add_x, start_y + stats_adjust_y + _add_y, steam_get_stat_int("shotby_bomber")); _add_y += 64; _add_x = 0;
		draw_text(start_x + _add_x, start_y + stats_adjust_y + _add_y, "shotby_rusher"); _add_x += 1536;	draw_text(start_x + _add_x, start_y + stats_adjust_y + _add_y, steam_get_stat_int("shotby_rusher")); _add_y += 64; _add_x = 0;
		draw_text(start_x + _add_x, start_y + stats_adjust_y + _add_y, "shotby_ranger"); _add_x += 1536;	draw_text(start_x + _add_x, start_y + stats_adjust_y + _add_y, steam_get_stat_int("shotby_ranger")); _add_y += 64; _add_x = 0;
		draw_text(start_x + _add_x, start_y + stats_adjust_y + _add_y, "shotby_gunship"); _add_x += 1536;	draw_text(start_x + _add_x, start_y + stats_adjust_y + _add_y, steam_get_stat_int("shotby_gunship")); _add_y += 64; _add_x = 0;
		draw_text(start_x + _add_x, start_y + stats_adjust_y + _add_y, "shotby_shotgunner"); _add_x += 1536;	draw_text(start_x + _add_x, start_y + stats_adjust_y + _add_y, steam_get_stat_int("shotby_shotgunner")); _add_y += 64; _add_x = 0;
		draw_text(start_x + _add_x, start_y + stats_adjust_y + _add_y, "shotby_destroyer"); _add_x += 1536;	draw_text(start_x + _add_x, start_y + stats_adjust_y + _add_y, steam_get_stat_int("shotby_destroyer")); _add_y += 64; _add_x = 0;
		draw_text(start_x + _add_x, start_y + stats_adjust_y + _add_y, "shotby_swarmer"); _add_x += 1536;	draw_text(start_x + _add_x, start_y + stats_adjust_y + _add_y, steam_get_stat_int("shotby_swarmer")); _add_y += 64; _add_x = 0;
		draw_text(start_x + _add_x, start_y + stats_adjust_y + _add_y, "shotby_heavy_cruiser"); _add_x += 1536;	draw_text(start_x + _add_x, start_y + stats_adjust_y + _add_y, steam_get_stat_int("shotby_heavy_cruiser")); _add_y += 64; _add_x = 0;
		draw_text(start_x + _add_x, start_y + stats_adjust_y + _add_y, "shotby_battlecruiser"); _add_x += 1536;	draw_text(start_x + _add_x, start_y + stats_adjust_y + _add_y, steam_get_stat_int("shotby_battlecruiser")); _add_y += 64; _add_x = 0;
		draw_text(start_x + _add_x, start_y + stats_adjust_y + _add_y, "shotby_turret_large"); _add_x += 1536;	draw_text(start_x + _add_x, start_y + stats_adjust_y + _add_y, steam_get_stat_int("shotby_turret_large")); _add_y += 64; _add_x = 0;
		draw_text(start_x + _add_x, start_y + stats_adjust_y + _add_y, "shotby_turret_laser"); _add_x += 1536;	draw_text(start_x + _add_x, start_y + stats_adjust_y + _add_y, steam_get_stat_int("shotby_turret_laser")); _add_y += 64; _add_x = 0;
		draw_text(start_x + _add_x, start_y + stats_adjust_y + _add_y, "shotby_turret_missile"); _add_x += 1536;	draw_text(start_x + _add_x, start_y + stats_adjust_y + _add_y, steam_get_stat_int("shotby_turret_missile")); _add_y += 64; _add_x = 0;
		draw_text(start_x + _add_x, start_y + stats_adjust_y + _add_y, "shotby_turret_ion"); _add_x += 1536;	draw_text(start_x + _add_x, start_y + stats_adjust_y + _add_y, steam_get_stat_int("shotby_turret_ion")); _add_y += 64; _add_x = 0;
		draw_text(start_x + _add_x, start_y + stats_adjust_y + _add_y, "shotby_turret_station"); _add_x += 1536	draw_text(start_x + _add_x, start_y + stats_adjust_y + _add_y, steam_get_stat_int("shotby_turret_station")); _add_y += 64; _add_x = 0;
		draw_text(start_x + _add_x, start_y + stats_adjust_y + _add_y, "shotby_turret_station_double"); _add_x += 1536	draw_text(start_x + _add_x, start_y + stats_adjust_y + _add_y, steam_get_stat_int("shotby_turret_station_double")); _add_y += 64; _add_x = 0;
		
		draw_text(start_x + _add_x, start_y + stats_adjust_y + _add_y, "total_deaths"); _add_x += 1536;	draw_text(start_x + _add_x, start_y + stats_adjust_y + _add_y, steam_get_stat_int("total_deaths")); _add_y += 64; _add_x = 0;
		draw_text(start_x + _add_x, start_y + stats_adjust_y + _add_y, "killedby_basic"); _add_x += 1536;	draw_text(start_x + _add_x, start_y + stats_adjust_y + _add_y, steam_get_stat_int("killedby_basic")); _add_y += 64; _add_x = 0;
		draw_text(start_x + _add_x, start_y + stats_adjust_y + _add_y, "killedby_suicider"); _add_x += 1536;	draw_text(start_x + _add_x, start_y + stats_adjust_y + _add_y, steam_get_stat_int("killedby_suicider")); _add_y += 64; _add_x = 0;
		draw_text(start_x + _add_x, start_y + stats_adjust_y + _add_y, "killedby_marauder"); _add_x += 1536;	draw_text(start_x + _add_x, start_y + stats_adjust_y + _add_y, steam_get_stat_int("killedby_marauder")); _add_y += 64; _add_x = 0;
		draw_text(start_x + _add_x, start_y + stats_adjust_y + _add_y, "killedby_ion"); _add_x += 1536;	draw_text(start_x + _add_x, start_y + stats_adjust_y + _add_y, steam_get_stat_int("killedby_ion")); _add_y += 64; _add_x = 0;
		draw_text(start_x + _add_x, start_y + stats_adjust_y + _add_y, "killedby_bomber"); _add_x += 1536;	draw_text(start_x + _add_x, start_y + stats_adjust_y + _add_y, steam_get_stat_int("killedby_bomber")); _add_y += 64; _add_x = 0;
		draw_text(start_x + _add_x, start_y + stats_adjust_y + _add_y, "killedby_rusher"); _add_x += 1536;	draw_text(start_x + _add_x, start_y + stats_adjust_y + _add_y, steam_get_stat_int("killedby_rusher")); _add_y += 64; _add_x = 0;
		draw_text(start_x + _add_x, start_y + stats_adjust_y + _add_y, "killedby_ranger"); _add_x += 1536;	draw_text(start_x + _add_x, start_y + stats_adjust_y + _add_y, steam_get_stat_int("killedby_ranger")); _add_y += 64; _add_x = 0;
		draw_text(start_x + _add_x, start_y + stats_adjust_y + _add_y, "killedby_gunship"); _add_x += 1536;	draw_text(start_x + _add_x, start_y + stats_adjust_y + _add_y, steam_get_stat_int("killedby_gunship")); _add_y += 64; _add_x = 0;
		draw_text(start_x + _add_x, start_y + stats_adjust_y + _add_y, "killedby_shotgunner"); _add_x += 1536;	draw_text(start_x + _add_x, start_y + stats_adjust_y + _add_y, steam_get_stat_int("killedby_shotgunner")); _add_y += 64; _add_x = 0;
		draw_text(start_x + _add_x, start_y + stats_adjust_y + _add_y, "killedby_destroyer"); _add_x += 1536;	draw_text(start_x + _add_x, start_y + stats_adjust_y + _add_y, steam_get_stat_int("killedby_destroyer")); _add_y += 64; _add_x = 0;
		draw_text(start_x + _add_x, start_y + stats_adjust_y + _add_y, "killedby_swarmer"); _add_x += 1536;	draw_text(start_x + _add_x, start_y + stats_adjust_y + _add_y, steam_get_stat_int("killedby_swarmer")); _add_y += 64; _add_x = 0;
		draw_text(start_x + _add_x, start_y + stats_adjust_y + _add_y, "killedby_heavy_cruiser"); _add_x += 1536;	draw_text(start_x + _add_x, start_y + stats_adjust_y + _add_y, steam_get_stat_int("killedby_heavy_cruiser")); _add_y += 64; _add_x = 0;
		draw_text(start_x + _add_x, start_y + stats_adjust_y + _add_y, "killedby_battlecruiser"); _add_x += 1536;	draw_text(start_x + _add_x, start_y + stats_adjust_y + _add_y, steam_get_stat_int("killedby_battlecruiser")); _add_y += 64; _add_x = 0;
		draw_text(start_x + _add_x, start_y + stats_adjust_y + _add_y, "killedby_turret_large"); _add_x += 1536;	draw_text(start_x + _add_x, start_y + stats_adjust_y + _add_y, steam_get_stat_int("killedby_turret_large")); _add_y += 64; _add_x = 0;
		draw_text(start_x + _add_x, start_y + stats_adjust_y + _add_y, "killedby_turret_laser"); _add_x += 1536;	draw_text(start_x + _add_x, start_y + stats_adjust_y + _add_y, steam_get_stat_int("killedby_turret_laser")); _add_y += 64; _add_x = 0;
		draw_text(start_x + _add_x, start_y + stats_adjust_y + _add_y, "killedby_turret_missile"); _add_x += 1536;	draw_text(start_x + _add_x, start_y + stats_adjust_y + _add_y, steam_get_stat_int("killedby_turret_missile")); _add_y += 64; _add_x = 0;
		draw_text(start_x + _add_x, start_y + stats_adjust_y + _add_y, "killedby_turret_ion"); _add_x += 1536;	draw_text(start_x + _add_x, start_y + stats_adjust_y + _add_y, steam_get_stat_int("killedby_turret_ion")); _add_y += 64; _add_x = 0;
		draw_text(start_x + _add_x, start_y + stats_adjust_y + _add_y, "killedby_asteroid"); _add_x += 1536;	draw_text(start_x + _add_x, start_y + stats_adjust_y + _add_y, steam_get_stat_int("killedby_asteroid")); _add_y += 64; _add_x = 0;
		draw_text(start_x + _add_x, start_y + stats_adjust_y + _add_y, "killedby_turret_station"); _add_x += 1536	draw_text(start_x + _add_x, start_y + stats_adjust_y + _add_y, steam_get_stat_int("killedby_turret_station")); _add_y += 64; _add_x = 0;
		draw_text(start_x + _add_x, start_y + stats_adjust_y + _add_y, "killedby_turret_station_double"); _add_x += 1536	draw_text(start_x + _add_x, start_y + stats_adjust_y + _add_y, steam_get_stat_int("killedby_turret_station_double")); _add_y += 64; _add_x = 0;
		
		draw_text(start_x + _add_x, start_y + stats_adjust_y + _add_y, "total_upgrades"); _add_x += 1536;	draw_text(start_x + _add_x, start_y + stats_adjust_y + _add_y, steam_get_stat_int("total_upgrades")); _add_y += 64; _add_x = 0;
		draw_text(start_x + _add_x, start_y + stats_adjust_y + _add_y, "upgrades_speed"); _add_x += 1536;	draw_text(start_x + _add_x, start_y + stats_adjust_y + _add_y, steam_get_stat_int("upgrades_speed")); _add_y += 64; _add_x = 0;
		draw_text(start_x + _add_x, start_y + stats_adjust_y + _add_y, "upgrades_turn_speed"); _add_x += 1536;	draw_text(start_x + _add_x, start_y + stats_adjust_y + _add_y, steam_get_stat_int("upgrades_turn_speed")); _add_y += 64; _add_x = 0;
		draw_text(start_x + _add_x, start_y + stats_adjust_y + _add_y, "upgrades_acceleration"); _add_x += 1536;	draw_text(start_x + _add_x, start_y + stats_adjust_y + _add_y, steam_get_stat_int("upgrades_acceleration")); _add_y += 64; _add_x = 0;
		draw_text(start_x + _add_x, start_y + stats_adjust_y + _add_y, "upgrades_aerodynamics"); _add_x += 1536;	draw_text(start_x + _add_x, start_y + stats_adjust_y + _add_y, steam_get_stat_int("upgrades_aerodynamics")); _add_y += 64; _add_x = 0;
		draw_text(start_x + _add_x, start_y + stats_adjust_y + _add_y, "upgrades_rammer"); _add_x += 1536;	draw_text(start_x + _add_x, start_y + stats_adjust_y + _add_y, steam_get_stat_int("upgrades_rammer")); _add_y += 64; _add_x = 0;
		draw_text(start_x + _add_x, start_y + stats_adjust_y + _add_y, "upgrades_drone_speed"); _add_x += 1536;	draw_text(start_x + _add_x, start_y + stats_adjust_y + _add_y, steam_get_stat_int("upgrades_drone_speed")); _add_y += 64; _add_x = 0;
		draw_text(start_x + _add_x, start_y + stats_adjust_y + _add_y, "upgrades_bullet_speed"); _add_x += 1536;	draw_text(start_x + _add_x, start_y + stats_adjust_y + _add_y, steam_get_stat_int("upgrades_bullet_speed")); _add_y += 64; _add_x = 0;
		draw_text(start_x + _add_x, start_y + stats_adjust_y + _add_y, "upgrades_shooting_speed"); _add_x += 1536;	draw_text(start_x + _add_x, start_y + stats_adjust_y + _add_y, steam_get_stat_int("upgrades_shooting_speed")); _add_y += 64; _add_x = 0;
		draw_text(start_x + _add_x, start_y + stats_adjust_y + _add_y, "upgrades_health"); _add_x += 1536;	draw_text(start_x + _add_x, start_y + stats_adjust_y + _add_y, steam_get_stat_int("upgrades_health")); _add_y += 64; _add_x = 0;
		draw_text(start_x + _add_x, start_y + stats_adjust_y + _add_y, "upgrades_healer_nanites"); _add_x += 1536;	draw_text(start_x + _add_x, start_y + stats_adjust_y + _add_y, steam_get_stat_int("upgrades_healer_nanites")); _add_y += 64; _add_x = 0;
		draw_text(start_x + _add_x, start_y + stats_adjust_y + _add_y, "upgrades_hull_upgrade"); _add_x += 1536;	draw_text(start_x + _add_x, start_y + stats_adjust_y + _add_y, steam_get_stat_int("upgrades_hull_upgrade")); _add_y += 64; _add_x = 0;
		draw_text(start_x + _add_x, start_y + stats_adjust_y + _add_y, "upgrades_shield"); _add_x += 1536;	draw_text(start_x + _add_x, start_y + stats_adjust_y + _add_y, steam_get_stat_int("upgrades_shield")); _add_y += 64; _add_x = 0;
		draw_text(start_x + _add_x, start_y + stats_adjust_y + _add_y, "upgrades_shield_strength"); _add_x += 1536;	draw_text(start_x + _add_x, start_y + stats_adjust_y + _add_y, steam_get_stat_int("upgrades_shield_strength")); _add_y += 64; _add_x = 0;
		draw_text(start_x + _add_x, start_y + stats_adjust_y + _add_y, "upgrades_shield_regen"); _add_x += 1536;	draw_text(start_x + _add_x, start_y + stats_adjust_y + _add_y, steam_get_stat_int("upgrades_shield_regen")); _add_y += 64; _add_x = 0;
		draw_text(start_x + _add_x, start_y + stats_adjust_y + _add_y, "upgrades_drone_ship"); _add_x += 1536;	draw_text(start_x + _add_x, start_y + stats_adjust_y + _add_y, steam_get_stat_int("upgrades_drone_ship")); _add_y += 64; _add_x = 0;
		draw_text(start_x + _add_x, start_y + stats_adjust_y + _add_y, "upgrades_drone_ai"); _add_x += 1536;	draw_text(start_x + _add_x, start_y + stats_adjust_y + _add_y, steam_get_stat_int("upgrades_drone_ai")); _add_y += 64; _add_x = 0;
		draw_text(start_x + _add_x, start_y + stats_adjust_y + _add_y, "upgrades_drone_hardware"); _add_x += 1536;	draw_text(start_x + _add_x, start_y + stats_adjust_y + _add_y, steam_get_stat_int("upgrades_drone_hardware")); _add_y += 64; _add_x = 0;
		draw_text(start_x + _add_x, start_y + stats_adjust_y + _add_y, "upgrades_drone_construction"); _add_x += 1536;	draw_text(start_x + _add_x, start_y + stats_adjust_y + _add_y, steam_get_stat_int("upgrades_drone_construction")); _add_y += 64; _add_x = 0;
		draw_text(start_x + _add_x, start_y + stats_adjust_y + _add_y, "upgrades_max_drones"); _add_x += 1536;	draw_text(start_x + _add_x, start_y + stats_adjust_y + _add_y, steam_get_stat_int("upgrades_max_drones")); _add_y += 64; _add_x = 0;
		draw_text(start_x + _add_x, start_y + stats_adjust_y + _add_y, "upgrades_single_shot"); _add_x += 1536;	draw_text(start_x + _add_x, start_y + stats_adjust_y + _add_y, steam_get_stat_int("upgrades_single_shot")); _add_y += 64; _add_x = 0;
		draw_text(start_x + _add_x, start_y + stats_adjust_y + _add_y, "upgrades_dual_shot"); _add_x += 1536;	draw_text(start_x + _add_x, start_y + stats_adjust_y + _add_y, steam_get_stat_int("upgrades_dual_shot")); _add_y += 64; _add_x = 0;
		draw_text(start_x + _add_x, start_y + stats_adjust_y + _add_y, "upgrades_triple_shot"); _add_x += 1536;	draw_text(start_x + _add_x, start_y + stats_adjust_y + _add_y, steam_get_stat_int("upgrades_triple_shot")); _add_y += 64; _add_x = 0;
		draw_text(start_x + _add_x, start_y + stats_adjust_y + _add_y, "upgrades_quad_shot"); _add_x += 1536;	draw_text(start_x + _add_x, start_y + stats_adjust_y + _add_y, steam_get_stat_int("upgrades_quad_shot")); _add_y += 64; _add_x = 0;
		draw_text(start_x + _add_x, start_y + stats_adjust_y + _add_y, "upgrades_gun_cooldown"); _add_x += 1536;	draw_text(start_x + _add_x, start_y + stats_adjust_y + _add_y, steam_get_stat_int("upgrades_gun_cooldown")); _add_y += 64; _add_x = 0;
		draw_text(start_x + _add_x, start_y + stats_adjust_y + _add_y, "upgrades_missiles"); _add_x += 1536;	draw_text(start_x + _add_x, start_y + stats_adjust_y + _add_y, steam_get_stat_int("upgrades_missiles")); _add_y += 64; _add_x = 0;
		draw_text(start_x + _add_x, start_y + stats_adjust_y + _add_y, "upgrades_dual_missiles"); _add_x += 1536;	draw_text(start_x + _add_x, start_y + stats_adjust_y + _add_y, steam_get_stat_int("upgrades_dual_missiles")); _add_y += 64; _add_x = 0;
		draw_text(start_x + _add_x, start_y + stats_adjust_y + _add_y, "upgrades_triple_missiles"); _add_x += 1536;	draw_text(start_x + _add_x, start_y + stats_adjust_y + _add_y, steam_get_stat_int("upgrades_triple_missiles")); _add_y += 64; _add_x = 0;
		draw_text(start_x + _add_x, start_y + stats_adjust_y + _add_y, "upgrades_missile_reload"); _add_x += 1536;	draw_text(start_x + _add_x, start_y + stats_adjust_y + _add_y, steam_get_stat_int("upgrades_missile_reload")); _add_y += 64; _add_x = 0;
		draw_text(start_x + _add_x, start_y + stats_adjust_y + _add_y, "upgrades_plated_missiles"); _add_x += 1536;	draw_text(start_x + _add_x, start_y + stats_adjust_y + _add_y, steam_get_stat_int("upgrades_plated_missiles")); _add_y += 64; _add_x = 0;
		draw_text(start_x + _add_x, start_y + stats_adjust_y + _add_y, "upgrades_missile_tracking"); _add_x += 1536;	draw_text(start_x + _add_x, start_y + stats_adjust_y + _add_y, steam_get_stat_int("upgrades_missile_tracking")); _add_y += 64; _add_x = 0;
		draw_text(start_x + _add_x, start_y + stats_adjust_y + _add_y, "upgrades_flak"); _add_x += 1536;	draw_text(start_x + _add_x, start_y + stats_adjust_y + _add_y, steam_get_stat_int("upgrades_flak")); _add_y += 64; _add_x = 0;
		draw_text(start_x + _add_x, start_y + stats_adjust_y + _add_y, "upgrades_flak_speed"); _add_x += 1536;	draw_text(start_x + _add_x, start_y + stats_adjust_y + _add_y, steam_get_stat_int("upgrades_flak_speed")); _add_y += 64; _add_x = 0;
		draw_text(start_x + _add_x, start_y + stats_adjust_y + _add_y, "upgrades_laser"); _add_x += 1536;	draw_text(start_x + _add_x, start_y + stats_adjust_y + _add_y, steam_get_stat_int("upgrades_laser")); _add_y += 64; _add_x = 0;
		draw_text(start_x + _add_x, start_y + stats_adjust_y + _add_y, "upgrades_dual_laser"); _add_x += 1536;	draw_text(start_x + _add_x, start_y + stats_adjust_y + _add_y, steam_get_stat_int("upgrades_dual_laser")); _add_y += 64; _add_x = 0;
		draw_text(start_x + _add_x, start_y + stats_adjust_y + _add_y, "upgrades_triple_laser"); _add_x += 1536;	draw_text(start_x + _add_x, start_y + stats_adjust_y + _add_y, steam_get_stat_int("upgrades_triple_laser")); _add_y += 64; _add_x = 0;
		draw_text(start_x + _add_x, start_y + stats_adjust_y + _add_y, "upgrades_quad_laser"); _add_x += 1536;	draw_text(start_x + _add_x, start_y + stats_adjust_y + _add_y, steam_get_stat_int("upgrades_quad_laser")); _add_y += 64; _add_x = 0;
		draw_text(start_x + _add_x, start_y + stats_adjust_y + _add_y, "upgrades_laser_cooldown"); _add_x += 1536;	draw_text(start_x + _add_x, start_y + stats_adjust_y + _add_y, steam_get_stat_int("upgrades_laser_cooldown")); _add_y += 64; _add_x = 0;
		draw_text(start_x + _add_x, start_y + stats_adjust_y + _add_y, "upgrades_missile_defense"); _add_x += 1536;	draw_text(start_x + _add_x, start_y + stats_adjust_y + _add_y, steam_get_stat_int("upgrades_missile_defense")); _add_y += 64; _add_x = 0;
		draw_text(start_x + _add_x, start_y + stats_adjust_y + _add_y, "upgrades_flank_laser"); _add_x += 1536;	draw_text(start_x + _add_x, start_y + stats_adjust_y + _add_y, steam_get_stat_int("upgrades_flank_laser")); _add_y += 64; _add_x = 0;
		draw_text(start_x + _add_x, start_y + stats_adjust_y + _add_y, "upgrades_ion_cannon"); _add_x += 1536;	draw_text(start_x + _add_x, start_y + stats_adjust_y + _add_y, steam_get_stat_int("upgrades_ion_cannon")); _add_y += 64; _add_x = 0;
		draw_text(start_x + _add_x, start_y + stats_adjust_y + _add_y, "upgrades_ion_recharge"); _add_x += 1536;	draw_text(start_x + _add_x, start_y + stats_adjust_y + _add_y, steam_get_stat_int("upgrades_ion_recharge")); _add_y += 64; _add_x = 0;
		draw_text(start_x + _add_x, start_y + stats_adjust_y + _add_y, "upgrades_cloaking_device"); _add_x += 1536;	draw_text(start_x + _add_x, start_y + stats_adjust_y + _add_y, steam_get_stat_int("upgrades_cloaking_device")); _add_y += 64; _add_x = 0;
		draw_text(start_x + _add_x, start_y + stats_adjust_y + _add_y, "upgrades_cloak_length"); _add_x += 1536;	draw_text(start_x + _add_x, start_y + stats_adjust_y + _add_y, steam_get_stat_int("upgrades_cloak_length")); _add_y += 64; _add_x = 0;
		draw_text(start_x + _add_x, start_y + stats_adjust_y + _add_y, "upgrades_cloak_recharge"); _add_x += 1536;	draw_text(start_x + _add_x, start_y + stats_adjust_y + _add_y, steam_get_stat_int("upgrades_cloak_recharge")); _add_y += 64; _add_x = 0;
		draw_text(start_x + _add_x, start_y + stats_adjust_y + _add_y, "upgrades_gun_turret"); _add_x += 1536;	draw_text(start_x + _add_x, start_y + stats_adjust_y + _add_y, steam_get_stat_int("upgrades_gun_turret")); _add_y += 64; _add_x = 0;
		draw_text(start_x + _add_x, start_y + stats_adjust_y + _add_y, "upgrades_missile_turret"); _add_x += 1536;	draw_text(start_x + _add_x, start_y + stats_adjust_y + _add_y, steam_get_stat_int("upgrades_missile_turret")); _add_y += 64; _add_x = 0;
		draw_text(start_x + _add_x, start_y + stats_adjust_y + _add_y, "upgrades_turret_cooldown"); _add_x += 1536;	draw_text(start_x + _add_x, start_y + stats_adjust_y + _add_y, steam_get_stat_int("upgrades_turret_cooldown")); _add_y += 64; _add_x = 0;
		draw_text(start_x + _add_x, start_y + stats_adjust_y + _add_y, "upgrades_missile_turret_cooldown"); _add_x += 1536;	draw_text(start_x + _add_x, start_y + stats_adjust_y + _add_y, steam_get_stat_int("upgrades_missile_turret_cooldown")); _add_y += 64; _add_x = 0;
		draw_text(start_x + _add_x, start_y + stats_adjust_y + _add_y, "upgrades_turret_turn_speed"); _add_x += 1536;	draw_text(start_x + _add_x, start_y + stats_adjust_y + _add_y, steam_get_stat_int("upgrades_turret_turn_speed")); _add_y += 64; _add_x = 0;
		draw_text(start_x + _add_x, start_y + stats_adjust_y + _add_y, "upgrades_missile_turret_turn_speed"); _add_x += 1536;	draw_text(start_x + _add_x, start_y + stats_adjust_y + _add_y, steam_get_stat_int("upgrades_missile_turret_turn_speed")); _add_y += 64; _add_x = 0;
		
		draw_text(start_x + _add_x, start_y + stats_adjust_y + _add_y, "total_enemy_shields_destroyed"); _add_x += 1536	draw_text(start_x + _add_x, start_y + stats_adjust_y + _add_y, steam_get_stat_int("total_enemy_shields_destroyed")); _add_y += 64; _add_x = 0;
		draw_text(start_x + _add_x, start_y + stats_adjust_y + _add_y, "total_enemy_shields_hit"); _add_x += 1536	draw_text(start_x + _add_x, start_y + stats_adjust_y + _add_y, steam_get_stat_int("total_enemy_shields_hit")); _add_y += 64; _add_x = 0;
		draw_text(start_x + _add_x, start_y + stats_adjust_y + _add_y, "enemy_shields_hitby_missile"); _add_x += 1536	draw_text(start_x + _add_x, start_y + stats_adjust_y + _add_y, steam_get_stat_int("enemy_shields_hitby_missile")); _add_y += 64; _add_x = 0;
		draw_text(start_x + _add_x, start_y + stats_adjust_y + _add_y, "enemy_shields_hitby_ion"); _add_x += 1536	draw_text(start_x + _add_x, start_y + stats_adjust_y + _add_y, steam_get_stat_int("enemy_shields_hitby_ion")); _add_y += 64; _add_x = 0;
		draw_text(start_x + _add_x, start_y + stats_adjust_y + _add_y, "enemy_shields_hitby_bullet"); _add_x += 1536	draw_text(start_x + _add_x, start_y + stats_adjust_y + _add_y, steam_get_stat_int("enemy_shields_hitby_bullet")); _add_y += 64; _add_x = 0;
		draw_text(start_x + _add_x, start_y + stats_adjust_y + _add_y, "total_player_shields_hit"); _add_x += 1536	draw_text(start_x + _add_x, start_y + stats_adjust_y + _add_y, steam_get_stat_int("total_player_shields_hit")); _add_y += 64; _add_x = 0;
		draw_text(start_x + _add_x, start_y + stats_adjust_y + _add_y, "player_shields_hitby_missile"); _add_x += 1536	draw_text(start_x + _add_x, start_y + stats_adjust_y + _add_y, steam_get_stat_int("player_shields_hitby_missile")); _add_y += 64; _add_x = 0;
		draw_text(start_x + _add_x, start_y + stats_adjust_y + _add_y, "player_shields_hitby_ion"); _add_x += 1536	draw_text(start_x + _add_x, start_y + stats_adjust_y + _add_y, steam_get_stat_int("player_shields_hitby_ion")); _add_y += 64; _add_x = 0;
		draw_text(start_x + _add_x, start_y + stats_adjust_y + _add_y, "player_shields_hitby_sniper"); _add_x += 1536	draw_text(start_x + _add_x, start_y + stats_adjust_y + _add_y, steam_get_stat_int("player_shields_hitby_sniper")); _add_y += 64; _add_x = 0;
		draw_text(start_x + _add_x, start_y + stats_adjust_y + _add_y, "player_shields_hitby_bullet"); _add_x += 1536	draw_text(start_x + _add_x, start_y + stats_adjust_y + _add_y, steam_get_stat_int("player_shields_hitby_bullet")); _add_y += 64; _add_x = 0;

		draw_text(start_x + _add_x, start_y + stats_adjust_y + _add_y, "total_drones_produced"); _add_x += 1536	draw_text(start_x + _add_x, start_y + stats_adjust_y + _add_y, steam_get_stat_int("total_drones_produced")); _add_y += 64; _add_x = 0;
		draw_text(start_x + _add_x, start_y + stats_adjust_y + _add_y, "drones_t1_produced"); _add_x += 1536	draw_text(start_x + _add_x, start_y + stats_adjust_y + _add_y, steam_get_stat_int("drones_t1_produced")); _add_y += 64; _add_x = 0;
		draw_text(start_x + _add_x, start_y + stats_adjust_y + _add_y, "drones_t2_produced"); _add_x += 1536	draw_text(start_x + _add_x, start_y + stats_adjust_y + _add_y, steam_get_stat_int("drones_t2_produced")); _add_y += 64; _add_x = 0;
		draw_text(start_x + _add_x, start_y + stats_adjust_y + _add_y, "drones_t3_produced"); _add_x += 1536	draw_text(start_x + _add_x, start_y + stats_adjust_y + _add_y, steam_get_stat_int("drones_t3_produced")); _add_y += 64; _add_x = 0;

		draw_text(start_x + _add_x, start_y + stats_adjust_y + _add_y, "player_bullets_shotby_flak"); _add_x += 1536	draw_text(start_x + _add_x, start_y + stats_adjust_y + _add_y, steam_get_stat_int("player_bullets_shotby_flak")); _add_y += 64; _add_x = 0;
		draw_text(start_x + _add_x, start_y + stats_adjust_y + _add_y, "player_missiles_shotby_flak"); _add_x += 1536	draw_text(start_x + _add_x, start_y + stats_adjust_y + _add_y, steam_get_stat_int("player_missiles_shotby_flak")); _add_y += 64; _add_x = 0;
		draw_text(start_x + _add_x, start_y + stats_adjust_y + _add_y, "enemy_bullets_shotby_flak"); _add_x += 1536	draw_text(start_x + _add_x, start_y + stats_adjust_y + _add_y, steam_get_stat_int("enemy_bullets_shotby_flak")); _add_y += 64; _add_x = 0;
		draw_text(start_x + _add_x, start_y + stats_adjust_y + _add_y, "enemy_missiles_shotby_flak"); _add_x += 1536	draw_text(start_x + _add_x, start_y + stats_adjust_y + _add_y, steam_get_stat_int("enemy_missiles_shotby_flak")); _add_y += 64; _add_x = 0;

		draw_text(start_x + _add_x, start_y + stats_adjust_y + _add_y, "enemies_rammed"); _add_x += 1536	draw_text(start_x + _add_x, start_y + stats_adjust_y + _add_y, steam_get_stat_int("enemies_rammed")); _add_y += 64; _add_x = 0;

	}
}