function sc_initialize_menu_stats_steam(){
	var s = 0;
	stats_menu[s] = "record_points"; 	stats_value[s] = steam_get_stat_int("record_points"); s++
	stats_menu[s] = "highest_wave"; 	stats_value[s] = steam_get_stat_int("highest_wave"); s++
	stats_menu[s] = "total_games"; 	stats_value[s] = steam_get_stat_int("total_games"); s++
	stats_menu[s] = "total_deaths"; 	stats_value[s] = steam_get_stat_int("total_deaths"); s++
	stats_menu[s] = "total_kills"; 	stats_value[s] = steam_get_stat_int("total_kills"); s++
	stats_menu[s] = "total_rounds"; 	stats_value[s] = steam_get_stat_int("total_rounds"); s++
	stats_menu[s] = "kills_basic"; 	stats_value[s] = steam_get_stat_int("kills_basic"); s++
	stats_menu[s] = "kills_suicider"; 	stats_value[s] = steam_get_stat_int("kills_suicider"); s++
	stats_menu[s] = "kills_marauder"; 	stats_value[s] = steam_get_stat_int("kills_marauder"); s++
	stats_menu[s] = "kills_ion"; 	stats_value[s] = steam_get_stat_int("kills_ion"); s++
	stats_menu[s] = "kills_bomber"; 	stats_value[s] = steam_get_stat_int("kills_bomber"); s++
	stats_menu[s] = "kills_sentinel"; 	stats_value[s] = steam_get_stat_int("kills_sentinel"); s++
	stats_menu[s] = "kills_rusher"; 	stats_value[s] = steam_get_stat_int("kills_rusher"); s++
	stats_menu[s] = "kills_sniper"; 	stats_value[s] = steam_get_stat_int("kills_sniper"); s++
	stats_menu[s] = "kills_gunship"; 	stats_value[s] = steam_get_stat_int("kills_gunship"); s++
	stats_menu[s] = "kills_shotgunner"; 	stats_value[s] = steam_get_stat_int("kills_shotgunner"); s++
	stats_menu[s] = "kills_destroyer"; 	stats_value[s] = steam_get_stat_int("kills_destroyer"); s++
	stats_menu[s] = "kills_swarmer"; 	stats_value[s] = steam_get_stat_int("kills_swarmer"); s++
	stats_menu[s] = "kills_heavy_cruiser"; 	stats_value[s] = steam_get_stat_int("kills_heavy_cruiser"); s++
	stats_menu[s] = "kills_battlecruiser"; 	stats_value[s] = steam_get_stat_int("kills_battlecruiser"); s++
	stats_menu[s] = "kills_turret_large"; 	stats_value[s] = steam_get_stat_int("kills_turret_large"); s++
	stats_menu[s] = "kills_turret_laser"; 	stats_value[s] = steam_get_stat_int("kills_turret_laser"); s++
	stats_menu[s] = "kills_turret_missile"; 	stats_value[s] = steam_get_stat_int("kills_turret_missile"); s++
	stats_menu[s] = "kills_turret_ion"; 	stats_value[s] = steam_get_stat_int("kills_turret_ion"); s++
	stats_menu[s] = "kills_station_hatch"; 	stats_value[s] = steam_get_stat_int("kills_station_hatch"); s++
	stats_menu[s] = "kills_station_rocket_launcher"; 	stats_value[s] = steam_get_stat_int("kills_station_rocket_launcher"); s++
	stats_menu[s] = "kills_station_hanger"; 	stats_value[s] = steam_get_stat_int("kills_station_hanger"); s++
	stats_menu[s] = "kills_station_shield"; 	stats_value[s] = steam_get_stat_int("kills_station_shield"); s++
	stats_menu[s] = "kills_station_core"; 	stats_value[s] = steam_get_stat_int("kills_station_core"); s++
	stats_menu[s] = "kills_turret_station"; 	stats_value[s] = steam_get_stat_int("kills_turret_station"); s++
	stats_menu[s] = "kills_turret_station_double"; 	stats_value[s] = steam_get_stat_int("kills_turret_station_double"); s++
	stats_menu[s] = "total_hitby"; 	stats_value[s] = steam_get_stat_int("total_hitby"); s++
	stats_menu[s] = "hitby_basic"; 	stats_value[s] = steam_get_stat_int("hitby_basic"); s++
	stats_menu[s] = "hitby_suicider"; 	stats_value[s] = steam_get_stat_int("hitby_suicider"); s++
	stats_menu[s] = "hitby_marauder"; 	stats_value[s] = steam_get_stat_int("hitby_marauder"); s++
	stats_menu[s] = "hitby_ion"; 	stats_value[s] = steam_get_stat_int("hitby_ion"); s++
	stats_menu[s] = "hitby_bomber"; 	stats_value[s] = steam_get_stat_int("hitby_bomber"); s++
	stats_menu[s] = "hitby_sentinel"; 	stats_value[s] = steam_get_stat_int("hitby_sentinel"); s++
	stats_menu[s] = "hitby_rusher"; 	stats_value[s] = steam_get_stat_int("hitby_rusher"); s++
	stats_menu[s] = "hitby_ranger"; 	stats_value[s] = steam_get_stat_int("hitby_ranger"); s++
	stats_menu[s] = "hitby_gunship"; 	stats_value[s] = steam_get_stat_int("hitby_gunship"); s++
	stats_menu[s] = "hitby_shotgunner"; 	stats_value[s] = steam_get_stat_int("hitby_shotgunner"); s++
	stats_menu[s] = "hitby_destroyer"; 	stats_value[s] = steam_get_stat_int("hitby_destroyer"); s++
	stats_menu[s] = "hitby_swarmer"; 	stats_value[s] = steam_get_stat_int("hitby_swarmer"); s++
	stats_menu[s] = "hitby_heavy_cruiser"; 	stats_value[s] = steam_get_stat_int("hitby_heavy_cruiser"); s++
	stats_menu[s] = "hitby_battlecruiser"; 	stats_value[s] = steam_get_stat_int("hitby_battlecruiser"); s++
	stats_menu[s] = "hitby_asteroid"; 	stats_value[s] = steam_get_stat_int("hitby_asteroid"); s++
	stats_menu[s] = "hitby_mine"; 	stats_value[s] = steam_get_stat_int("hitby_mine"); s++
	stats_menu[s] = "total_shotby"; 	stats_value[s] = steam_get_stat_int("total_shotby"); s++
	stats_menu[s] = "total_shotby_ion"; 	stats_value[s] = steam_get_stat_int("total_shotby_ion"); s++
	stats_menu[s] = "total_shotby_laser"; 	stats_value[s] = steam_get_stat_int("total_shotby_laser"); s++
	stats_menu[s] = "total_shotby_missile"; 	stats_value[s] = steam_get_stat_int("total_shotby_missile"); s++
	stats_menu[s] = "total_shotby_bullet"; 	stats_value[s] = steam_get_stat_int("total_shotby_bullet"); s++
	stats_menu[s] = "total_shotby_sniper"; 	stats_value[s] = steam_get_stat_int("total_shotby_sniper"); s++
	stats_menu[s] = "total_shotby_station_bullet"; 	stats_value[s] = steam_get_stat_int("total_shotby_station_bullet"); s++
	stats_menu[s] = "shotby_basic"; 	stats_value[s] = steam_get_stat_int("shotby_basic"); s++
	stats_menu[s] = "shotby_suicider"; 	stats_value[s] = steam_get_stat_int("shotby_suicider"); s++
	stats_menu[s] = "shotby_marauder"; 	stats_value[s] = steam_get_stat_int("shotby_marauder"); s++
	stats_menu[s] = "shotby_ion"; 	stats_value[s] = steam_get_stat_int("shotby_ion"); s++
	stats_menu[s] = "shotby_bomber"; 	stats_value[s] = steam_get_stat_int("shotby_bomber"); s++
	stats_menu[s] = "shotby_sentinel"; 	stats_value[s] = steam_get_stat_int("shotby_sentinel"); s++
	stats_menu[s] = "shotby_rusher"; 	stats_value[s] = steam_get_stat_int("shotby_rusher"); s++
	stats_menu[s] = "shotby_ranger"; 	stats_value[s] = steam_get_stat_int("shotby_ranger"); s++
	stats_menu[s] = "shotby_gunship"; 	stats_value[s] = steam_get_stat_int("shotby_gunship"); s++
	stats_menu[s] = "shotby_shotgunner"; 	stats_value[s] = steam_get_stat_int("shotby_shotgunner"); s++
	stats_menu[s] = "shotby_destroyer"; 	stats_value[s] = steam_get_stat_int("shotby_destroyer"); s++
	stats_menu[s] = "shotby_swarmer"; 	stats_value[s] = steam_get_stat_int("shotby_swarmer"); s++
	stats_menu[s] = "shotby_heavy_cruiser"; 	stats_value[s] = steam_get_stat_int("shotby_heavy_cruiser"); s++
	stats_menu[s] = "shotby_battlecruiser"; 	stats_value[s] = steam_get_stat_int("shotby_battlecruiser"); s++
	stats_menu[s] = "shotby_turret_large"; 	stats_value[s] = steam_get_stat_int("shotby_turret_large"); s++
	stats_menu[s] = "shotby_turret_laser"; 	stats_value[s] = steam_get_stat_int("shotby_turret_laser"); s++
	stats_menu[s] = "shotby_turret_missile"; 	stats_value[s] = steam_get_stat_int("shotby_turret_missile"); s++
	stats_menu[s] = "shotby_turret_ion"; 	stats_value[s] = steam_get_stat_int("shotby_turret_ion"); s++
	stats_menu[s] = "shotby_turret_station_double"; 	stats_value[s] = steam_get_stat_int("shotby_turret_station_double"); s++
	stats_menu[s] = "shotby_turret_station"; 	stats_value[s] = steam_get_stat_int("shotby_turret_station"); s++
	stats_menu[s] = "total_deaths"; 	stats_value[s] = steam_get_stat_int("total_deaths"); s++
	stats_menu[s] = "killedby_basic"; 	stats_value[s] = steam_get_stat_int("killedby_basic"); s++
	stats_menu[s] = "killedby_suicider"; 	stats_value[s] = steam_get_stat_int("killedby_suicider"); s++
	stats_menu[s] = "killedby_marauder"; 	stats_value[s] = steam_get_stat_int("killedby_marauder"); s++
	stats_menu[s] = "killedby_ion"; 	stats_value[s] = steam_get_stat_int("killedby_ion"); s++
	stats_menu[s] = "killedby_bomber"; 	stats_value[s] = steam_get_stat_int("killedby_bomber"); s++
	stats_menu[s] = "killedby_sentinel"; 	stats_value[s] = steam_get_stat_int("killedby_sentinel"); s++
	stats_menu[s] = "killedby_rusher"; 	stats_value[s] = steam_get_stat_int("killedby_rusher"); s++
	stats_menu[s] = "killedby_ranger"; 	stats_value[s] = steam_get_stat_int("killedby_ranger"); s++
	stats_menu[s] = "killedby_gunship"; 	stats_value[s] = steam_get_stat_int("killedby_gunship"); s++
	stats_menu[s] = "killedby_shotgunner"; 	stats_value[s] = steam_get_stat_int("killedby_shotgunner"); s++
	stats_menu[s] = "killedby_destroyer"; 	stats_value[s] = steam_get_stat_int("killedby_destroyer"); s++
	stats_menu[s] = "killedby_swarmer"; 	stats_value[s] = steam_get_stat_int("killedby_swarmer"); s++
	stats_menu[s] = "killedby_heavy_cruiser"; 	stats_value[s] = steam_get_stat_int("killedby_heavy_cruiser"); s++
	stats_menu[s] = "killedby_battlecruiser"; 	stats_value[s] = steam_get_stat_int("killedby_battlecruiser"); s++
	stats_menu[s] = "killedby_turret_large"; 	stats_value[s] = steam_get_stat_int("killedby_turret_large"); s++
	stats_menu[s] = "killedby_turret_laser"; 	stats_value[s] = steam_get_stat_int("killedby_turret_laser"); s++
	stats_menu[s] = "killedby_turret_missile"; 	stats_value[s] = steam_get_stat_int("killedby_turret_missile"); s++
	stats_menu[s] = "killedby_turret_ion"; 	stats_value[s] = steam_get_stat_int("killedby_turret_ion"); s++
	stats_menu[s] = "killedby_turret_station"; 	stats_value[s] = steam_get_stat_int("killedby_turret_station"); s++
	stats_menu[s] = "killedby_turret_station_double"; 	stats_value[s] = steam_get_stat_int("killedby_turret_station_double"); s++
	stats_menu[s] = "killedby_asteroid"; 	stats_value[s] = steam_get_stat_int("killedby_asteroid"); s++
	stats_menu[s] = "total_upgrades"; 	stats_value[s] = steam_get_stat_int("total_upgrades"); s++
	stats_menu[s] = "upgrades_speed"; 	stats_value[s] = steam_get_stat_int("upgrades_speed"); s++
	stats_menu[s] = "upgrades_turn_speed"; 	stats_value[s] = steam_get_stat_int("upgrades_turn_speed"); s++
	stats_menu[s] = "upgrades_acceleration"; 	stats_value[s] = steam_get_stat_int("upgrades_acceleration"); s++
	stats_menu[s] = "upgrades_aerodynamics"; 	stats_value[s] = steam_get_stat_int("upgrades_aerodynamics"); s++
	stats_menu[s] = "upgrades_rammer"; 	stats_value[s] = steam_get_stat_int("upgrades_rammer"); s++
	stats_menu[s] = "upgrades_drone_speed"; 	stats_value[s] = steam_get_stat_int("upgrades_drone_speed"); s++
	stats_menu[s] = "upgrades_bullet_speed"; 	stats_value[s] = steam_get_stat_int("upgrades_bullet_speed"); s++
	stats_menu[s] = "upgrades_shooting_speed"; 	stats_value[s] = steam_get_stat_int("upgrades_shooting_speed"); s++
	stats_menu[s] = "upgrades_health"; 	stats_value[s] = steam_get_stat_int("upgrades_health"); s++
	stats_menu[s] = "upgrades_healer_nanites"; 	stats_value[s] = steam_get_stat_int("upgrades_healer_nanites"); s++
	stats_menu[s] = "upgrades_hull_upgrade"; 	stats_value[s] = steam_get_stat_int("upgrades_hull_upgrade"); s++
	stats_menu[s] = "upgrades_shield"; 	stats_value[s] = steam_get_stat_int("upgrades_shield"); s++
	stats_menu[s] = "upgrades_shield_strength"; 	stats_value[s] = steam_get_stat_int("upgrades_shield_strength"); s++
	stats_menu[s] = "upgrades_shield_regen"; 	stats_value[s] = steam_get_stat_int("upgrades_shield_regen"); s++
	stats_menu[s] = "upgrades_drone_ship"; 	stats_value[s] = steam_get_stat_int("upgrades_drone_ship"); s++
	stats_menu[s] = "upgrades_drone_ai"; 	stats_value[s] = steam_get_stat_int("upgrades_drone_ai"); s++
	stats_menu[s] = "upgrades_drone_hardware"; 	stats_value[s] = steam_get_stat_int("upgrades_drone_hardware"); s++
	stats_menu[s] = "upgrades_drone_construction"; 	stats_value[s] = steam_get_stat_int("upgrades_drone_construction"); s++
	stats_menu[s] = "upgrades_max_drones"; 	stats_value[s] = steam_get_stat_int("upgrades_max_drones"); s++
	stats_menu[s] = "upgrades_single_shot"; 	stats_value[s] = steam_get_stat_int("upgrades_single_shot"); s++
	stats_menu[s] = "upgrades_dual_shot"; 	stats_value[s] = steam_get_stat_int("upgrades_dual_shot"); s++
	stats_menu[s] = "upgrades_triple_shot"; 	stats_value[s] = steam_get_stat_int("upgrades_triple_shot"); s++
	stats_menu[s] = "upgrades_quad_shot"; 	stats_value[s] = steam_get_stat_int("upgrades_quad_shot"); s++
	stats_menu[s] = "upgrades_gun_cooldown"; 	stats_value[s] = steam_get_stat_int("upgrades_gun_cooldown"); s++
	stats_menu[s] = "upgrades_missiles"; 	stats_value[s] = steam_get_stat_int("upgrades_missiles"); s++
	stats_menu[s] = "upgrades_dual_missiles"; 	stats_value[s] = steam_get_stat_int("upgrades_dual_missiles"); s++
	stats_menu[s] = "upgrades_triple_missiles"; 	stats_value[s] = steam_get_stat_int("upgrades_triple_missiles"); s++
	stats_menu[s] = "upgrades_missile_reload"; 	stats_value[s] = steam_get_stat_int("upgrades_missile_reload"); s++
	stats_menu[s] = "upgrades_plated_missiles"; 	stats_value[s] = steam_get_stat_int("upgrades_plated_missiles"); s++
	stats_menu[s] = "upgrades_missile_tracking"; 	stats_value[s] = steam_get_stat_int("upgrades_missile_tracking"); s++
	stats_menu[s] = "upgrades_flak"; 	stats_value[s] = steam_get_stat_int("upgrades_flak"); s++
	stats_menu[s] = "upgrades_flak_speed"; 	stats_value[s] = steam_get_stat_int("upgrades_flak_speed"); s++
	stats_menu[s] = "upgrades_laser"; 	stats_value[s] = steam_get_stat_int("upgrades_laser"); s++
	stats_menu[s] = "upgrades_dual_laser"; 	stats_value[s] = steam_get_stat_int("upgrades_dual_laser"); s++
	stats_menu[s] = "upgrades_triple_laser"; 	stats_value[s] = steam_get_stat_int("upgrades_triple_laser"); s++
	stats_menu[s] = "upgrades_quad_laser"; 	stats_value[s] = steam_get_stat_int("upgrades_quad_laser"); s++
	stats_menu[s] = "upgrades_laser_cooldown"; 	stats_value[s] = steam_get_stat_int("upgrades_laser_cooldown"); s++
	stats_menu[s] = "upgrades_missile_defense"; 	stats_value[s] = steam_get_stat_int("upgrades_missile_defense"); s++
	stats_menu[s] = "upgrades_flank_laser"; 	stats_value[s] = steam_get_stat_int("upgrades_flank_laser"); s++
	stats_menu[s] = "upgrades_ion_cannon"; 	stats_value[s] = steam_get_stat_int("upgrades_ion_cannon"); s++
	stats_menu[s] = "upgrades_ion_recharge"; 	stats_value[s] = steam_get_stat_int("upgrades_ion_recharge"); s++
	stats_menu[s] = "upgrades_cloaking_device"; 	stats_value[s] = steam_get_stat_int("upgrades_cloaking_device"); s++
	stats_menu[s] = "upgrades_cloak_length"; 	stats_value[s] = steam_get_stat_int("upgrades_cloak_length"); s++
	stats_menu[s] = "upgrades_cloak_recharge"; 	stats_value[s] = steam_get_stat_int("upgrades_cloak_recharge"); s++
	stats_menu[s] = "upgrades_gun_turret"; 	stats_value[s] = steam_get_stat_int("upgrades_gun_turret"); s++
	stats_menu[s] = "upgrades_missile_turret"; 	stats_value[s] = steam_get_stat_int("upgrades_missile_turret"); s++
	stats_menu[s] = "upgrades_turret_cooldown"; 	stats_value[s] = steam_get_stat_int("upgrades_turret_cooldown"); s++
	stats_menu[s] = "upgrades_missile_turret_cooldown"; 	stats_value[s] = steam_get_stat_int("upgrades_missile_turret_cooldown"); s++
	stats_menu[s] = "upgrades_turret_turn_speed"; 	stats_value[s] = steam_get_stat_int("upgrades_turret_turn_speed"); s++
	stats_menu[s] = "upgrades_missile_turret_turn_speed"; 	stats_value[s] = steam_get_stat_int("upgrades_missile_turret_turn_speed"); s++
	stats_menu[s] = "total_enemy_shields_destroyed"; 	stats_value[s] = steam_get_stat_int("total_enemy_shields_destroyed"); s++
	stats_menu[s] = "total_enemy_shields_hit"; 	stats_value[s] = steam_get_stat_int("total_enemy_shields_hit"); s++
	stats_menu[s] = "enemy_shields_hitby_missile"; 	stats_value[s] = steam_get_stat_int("enemy_shields_hitby_missile"); s++
	stats_menu[s] = "enemy_shields_hitby_ion"; 	stats_value[s] = steam_get_stat_int("enemy_shields_hitby_ion"); s++
	stats_menu[s] = "enemy_shields_hitby_bullet"; 	stats_value[s] = steam_get_stat_int("enemy_shields_hitby_bullet"); s++
	stats_menu[s] = "total_player_shields_hit"; 	stats_value[s] = steam_get_stat_int("total_player_shields_hit"); s++
	stats_menu[s] = "player_shields_hitby_missile"; 	stats_value[s] = steam_get_stat_int("player_shields_hitby_missile"); s++
	stats_menu[s] = "player_shields_hitby_ion"; 	stats_value[s] = steam_get_stat_int("player_shields_hitby_ion"); s++
	stats_menu[s] = "player_shields_hitby_sniper"; 	stats_value[s] = steam_get_stat_int("player_shields_hitby_sniper"); s++
	stats_menu[s] = "player_shields_hitby_bullet"; 	stats_value[s] = steam_get_stat_int("player_shields_hitby_bullet"); s++
	stats_menu[s] = "total_drones_produced"; 	stats_value[s] = steam_get_stat_int("total_drones_produced"); s++
	stats_menu[s] = "drones_t1_produced"; 	stats_value[s] = steam_get_stat_int("drones_t1_produced"); s++
	stats_menu[s] = "drones_t2_produced"; 	stats_value[s] = steam_get_stat_int("drones_t2_produced"); s++
	stats_menu[s] = "drones_t3_produced"; 	stats_value[s] = steam_get_stat_int("drones_t3_produced"); s++
	stats_menu[s] = "player_bullets_shotby_flak"; 	stats_value[s] = steam_get_stat_int("player_bullets_shotby_flak"); s++
	stats_menu[s] = "player_missiles_shotby_flak"; 	stats_value[s] = steam_get_stat_int("player_missiles_shotby_flak"); s++
	stats_menu[s] = "enemy_bullets_shotby_flak"; 	stats_value[s] = steam_get_stat_int("enemy_bullets_shotby_flak"); s++
	stats_menu[s] = "enemy_missiles_shotby_flak"; 	stats_value[s] = steam_get_stat_int("enemy_missiles_shotby_flak"); s++
	stats_menu[s] = "enemies_rammed"; 	stats_value[s] = steam_get_stat_int("enemies_rammed"); s++
	stats_menu[s] = "killedby_enemy_other"; 	stats_value[s] = steam_get_stat_int("killedby_enemy_other"); s++
	stats_menu[s] = "hitby_enemy_other"; 	stats_value[s] = steam_get_stat_int("hitby_enemy_other"); s++
	stats_menu[s] = "total_shotby_other"; 	stats_value[s] = steam_get_stat_int("total_shotby_other"); s++
	stats_menu[s] = "shotby_enemy_other"; 	stats_value[s] = steam_get_stat_int("shotby_enemy_other"); s++
	
	for (var i = 0; i < array_length(stats_menu); i++) {
		while string_width(stats_menu[i]) < stats_width {
			stats_menu[i] = stats_menu[i] + ".";
		}
	}
}