function sc_initialize_menu_achievements() {
	achievements_adjust_y = 0;
	
	enum ach {
		ach_point_500,
		ach_point_2500,
		ach_point_5000,
		ach_point_10000,
		ach_point_25000,
		ach_point_50000,
		ach_point_75000,
		ach_point_100000,
		ach_station_destroyed,
		ach_kills_basic_1,
		ach_kills_basic_25,
		ach_kills_basic_100,
		ach_kills_basic_250,
		ach_kills_basic_1000,
		ach_kills_basic_2500,
		ach_kills_basic_10000,
		ach_kills_suicider_1,
		ach_kills_suicider_25,
		ach_kills_suicider_100,
		ach_kills_suicider_250,
		ach_kills_suicider_1000,
		ach_kills_suicider_2500,
		ach_kills_suicider_10000,
		ach_kills_marauder_1,
		ach_kills_marauder_25,
		ach_kills_marauder_100,
		ach_kills_marauder_250,
		ach_kills_marauder_1000,
		ach_kills_marauder_2500,
		ach_kills_marauder_10000,
		ach_kills_ion_1,
		ach_kills_ion_25,
		ach_kills_ion_100,
		ach_kills_ion_250,
		ach_kills_ion_1000,
		ach_kills_ion_2500,
		ach_kills_ion_10000,
		ach_kills_bomber_1,
		ach_kills_bomber_25,
		ach_kills_bomber_100,
		ach_kills_bomber_250,
		ach_kills_bomber_1000,
		ach_kills_bomber_2500,
		ach_kills_bomber_10000,
		ach_kills_rusher_1,
		ach_kills_rusher_25,
		ach_kills_rusher_100,
		ach_kills_rusher_250,
		ach_kills_rusher_1000,
		ach_kills_rusher_2500,
		ach_kills_rusher_10000,
		ach_kills_ranger_1,
		ach_kills_ranger_25,
		ach_kills_ranger_100,
		ach_kills_ranger_250,
		ach_kills_ranger_1000,
		ach_kills_ranger_2500,
		ach_kills_ranger_10000,
		ach_kills_gunship_1,
		ach_kills_gunship_25,
		ach_kills_gunship_100,
		ach_kills_gunship_250,
		ach_kills_gunship_1000,
		ach_kills_gunship_2500,
		ach_kills_gunship_10000,
		ach_kills_destroyer_1,
		ach_kills_destroyer_25,
		ach_kills_destroyer_100,
		ach_kills_destroyer_250,
		ach_kills_destroyer_1000,
		ach_kills_destroyer_2500,
		ach_kills_destroyer_10000,
		ach_kills_shotgunner_1,
		ach_kills_shotgunner_25,
		ach_kills_shotgunner_100,
		ach_kills_shotgunner_250,
		ach_kills_shotgunner_1000,
		ach_kills_shotgunner_2500,
		ach_kills_shotgunner_10000,
		ach_kills_swarmer_1,
		ach_kills_swarmer_25,
		ach_kills_swarmer_100,
		ach_kills_swarmer_250,
		ach_kills_swarmer_1000,
		ach_kills_swarmer_2500,
		ach_kills_swarmer_10000,
		ach_kills_heavy_cruiser_1,
		ach_kills_heavy_cruiser_25,
		ach_kills_heavy_cruiser_100,
		ach_kills_battlecruiser_1,
		ach_kills_battlecruiser_10,
		ach_kills_battlecruiser_25,
		ach_wave_1,
		ach_wave_5,
		ach_wave_10,
		ach_wave_25,
		ach_wave_50,
		ach_wave_80,
		ach_wave_100
	}
	
	achievements[ach.ach_point_500, 0] = steam_get_stat_int("record_points");	achievements[ach.ach_point_500, 1] = "500 Points";	achievements[ach.ach_point_500, 2] = "Get 500 points";	achievements[ach.ach_point_500, 3] = s_ach_points;	achievements[ach.ach_point_500, 4] = 0;	achievements[ach.ach_point_500, 5] = 1;	achievements[ach.ach_point_500, 6] = 500;	achievements[ach.ach_point_500, 7] = steam_get_achievement("ach_point_500");
	achievements[ach.ach_point_2500, 0] = steam_get_stat_int("record_points");	achievements[ach.ach_point_2500, 1] = "2,500 Points";	achievements[ach.ach_point_2500, 2] = "Get 2,500 points";	achievements[ach.ach_point_2500, 3] = s_ach_points;	achievements[ach.ach_point_2500, 4] = 2;	achievements[ach.ach_point_2500, 5] = 3;	achievements[ach.ach_point_2500, 6] = 2500;	achievements[ach.ach_point_2500, 7] = steam_get_achievement("ach_point_2500");
	achievements[ach.ach_point_5000, 0] = steam_get_stat_int("record_points");	achievements[ach.ach_point_5000, 1] = "5,000 Points";	achievements[ach.ach_point_5000, 2] = "Get 5,000 points";	achievements[ach.ach_point_5000, 3] = s_ach_points;	achievements[ach.ach_point_5000, 4] = 4;	achievements[ach.ach_point_5000, 5] = 5;	achievements[ach.ach_point_5000, 6] = 5000;	achievements[ach.ach_point_5000, 7] = steam_get_achievement("ach_point_5000");
	achievements[ach.ach_point_10000, 0] = steam_get_stat_int("record_points");	achievements[ach.ach_point_10000, 1] = "10,000 Points";	achievements[ach.ach_point_10000, 2] = "Get 10,000 points";	achievements[ach.ach_point_10000, 3] = s_ach_points;	achievements[ach.ach_point_10000, 4] = 6;	achievements[ach.ach_point_10000, 5] = 7;	achievements[ach.ach_point_10000, 6] = 10000;	achievements[ach.ach_point_10000, 7] = steam_get_achievement("ach_point_10000");
	achievements[ach.ach_point_25000, 0] = steam_get_stat_int("record_points");	achievements[ach.ach_point_25000, 1] = "25,000 Points";	achievements[ach.ach_point_25000, 2] = "Get 25,000 points";	achievements[ach.ach_point_25000, 3] = s_ach_points;	achievements[ach.ach_point_25000, 4] = 8;	achievements[ach.ach_point_25000, 5] = 9;	achievements[ach.ach_point_25000, 6] = 25000;	achievements[ach.ach_point_25000, 7] = steam_get_achievement("ach_point_25000");
	achievements[ach.ach_point_50000, 0] = steam_get_stat_int("record_points");	achievements[ach.ach_point_50000, 1] = "50,000 Points";	achievements[ach.ach_point_50000, 2] = "Get 50,000 points";	achievements[ach.ach_point_50000, 3] = s_ach_points;	achievements[ach.ach_point_50000, 4] = 10;	achievements[ach.ach_point_50000, 5] = 11;	achievements[ach.ach_point_50000, 6] = 50000;	achievements[ach.ach_point_50000, 7] = steam_get_achievement("ach_point_50000");
	achievements[ach.ach_point_75000, 0] = steam_get_stat_int("record_points");	achievements[ach.ach_point_75000, 1] = "75,000 Points";	achievements[ach.ach_point_75000, 2] = "Get 75,000 points";	achievements[ach.ach_point_75000, 3] = s_ach_points;	achievements[ach.ach_point_75000, 4] = 12;	achievements[ach.ach_point_75000, 5] = 13;	achievements[ach.ach_point_75000, 6] = 75000;	achievements[ach.ach_point_75000, 7] = steam_get_achievement("ach_point_75000");
	achievements[ach.ach_point_100000, 0] = steam_get_stat_int("record_points");	achievements[ach.ach_point_100000, 1] = "100,000 Points";	achievements[ach.ach_point_100000, 2] = "Get 100,000 points";	achievements[ach.ach_point_100000, 3] = s_ach_points;	achievements[ach.ach_point_100000, 4] = 14;	achievements[ach.ach_point_100000, 5] = 15;	achievements[ach.ach_point_100000, 6] = 100000;	achievements[ach.ach_point_100000, 7] = steam_get_achievement("ach_point_100000");
	achievements[ach.ach_station_destroyed, 0] = steam_get_stat_int("kills_station_core");	achievements[ach.ach_station_destroyed, 1] = "Station Down";	achievements[ach.ach_station_destroyed, 2] = "Destroy a station";	achievements[ach.ach_station_destroyed, 3] = s_ach_station_destroyed;	achievements[ach.ach_station_destroyed, 4] = 0;	achievements[ach.ach_station_destroyed, 5] = 1;	achievements[ach.ach_station_destroyed, 6] = 1;	achievements[ach.ach_station_destroyed, 7] = steam_get_achievement("ach_station_destroyed");
	achievements[ach.ach_kills_basic_1, 0] = steam_get_stat_int("kills_basic");	achievements[ach.ach_kills_basic_1, 1] = "1 Fighter";	achievements[ach.ach_kills_basic_1, 2] = "Destroy 1 fighter";	achievements[ach.ach_kills_basic_1, 3] = s_ach_enemies;	achievements[ach.ach_kills_basic_1, 4] = 1;	achievements[ach.ach_kills_basic_1, 5] = 0;	achievements[ach.ach_kills_basic_1, 6] = 1;	achievements[ach.ach_kills_basic_1, 7] = steam_get_achievement("ach_kills_basic_1");
	achievements[ach.ach_kills_basic_25, 0] = steam_get_stat_int("kills_basic");	achievements[ach.ach_kills_basic_25, 1] = "25 Fighters";	achievements[ach.ach_kills_basic_25, 2] = "Destroy 25 fighters";	achievements[ach.ach_kills_basic_25, 3] = s_ach_enemies;	achievements[ach.ach_kills_basic_25, 4] = 2;	achievements[ach.ach_kills_basic_25, 5] = 0;	achievements[ach.ach_kills_basic_25, 6] = 25;	achievements[ach.ach_kills_basic_25, 7] = steam_get_achievement("ach_kills_basic_25");
	achievements[ach.ach_kills_basic_100, 0] = steam_get_stat_int("kills_basic");	achievements[ach.ach_kills_basic_100, 1] = "100 Fighters";	achievements[ach.ach_kills_basic_100, 2] = "Destroy 100 fighters";	achievements[ach.ach_kills_basic_100, 3] = s_ach_enemies;	achievements[ach.ach_kills_basic_100, 4] = 3;	achievements[ach.ach_kills_basic_100, 5] = 0;	achievements[ach.ach_kills_basic_100, 6] = 100;	achievements[ach.ach_kills_basic_100, 7] = steam_get_achievement("ach_kills_basic_100");
	achievements[ach.ach_kills_basic_250, 0] = steam_get_stat_int("kills_basic");	achievements[ach.ach_kills_basic_250, 1] = "250 Fighters";	achievements[ach.ach_kills_basic_250, 2] = "Destroy 250 fighters";	achievements[ach.ach_kills_basic_250, 3] = s_ach_enemies;	achievements[ach.ach_kills_basic_250, 4] = 4;	achievements[ach.ach_kills_basic_250, 5] = 0;	achievements[ach.ach_kills_basic_250, 6] = 250;	achievements[ach.ach_kills_basic_250, 7] = steam_get_achievement("ach_kills_basic_250");
	achievements[ach.ach_kills_basic_1000, 0] = steam_get_stat_int("kills_basic");	achievements[ach.ach_kills_basic_1000, 1] = "1,000 Fighters";	achievements[ach.ach_kills_basic_1000, 2] = "Destroy 1,000 fighters";	achievements[ach.ach_kills_basic_1000, 3] = s_ach_enemies;	achievements[ach.ach_kills_basic_1000, 4] = 5;	achievements[ach.ach_kills_basic_1000, 5] = 0;	achievements[ach.ach_kills_basic_1000, 6] = 1000;	achievements[ach.ach_kills_basic_1000, 7] = steam_get_achievement("ach_kills_basic_1000");
	achievements[ach.ach_kills_basic_2500, 0] = steam_get_stat_int("kills_basic");	achievements[ach.ach_kills_basic_2500, 1] = "2,500 Fighters";	achievements[ach.ach_kills_basic_2500, 2] = "Destroy 2,500 fighters";	achievements[ach.ach_kills_basic_2500, 3] = s_ach_enemies;	achievements[ach.ach_kills_basic_2500, 4] = 6;	achievements[ach.ach_kills_basic_2500, 5] = 0;	achievements[ach.ach_kills_basic_2500, 6] = 2500;	achievements[ach.ach_kills_basic_2500, 7] = steam_get_achievement("ach_kills_basic_2500");
	achievements[ach.ach_kills_basic_10000, 0] = steam_get_stat_int("kills_basic");	achievements[ach.ach_kills_basic_10000, 1] = "10,000 Fighters";	achievements[ach.ach_kills_basic_10000, 2] = "Destroy 10,000 fighters";	achievements[ach.ach_kills_basic_10000, 3] = s_ach_enemies;	achievements[ach.ach_kills_basic_10000, 4] = 7;	achievements[ach.ach_kills_basic_10000, 5] = 0;	achievements[ach.ach_kills_basic_10000, 6] = 10000;	achievements[ach.ach_kills_basic_10000, 7] = steam_get_achievement("ach_kills_basic_10000");
	achievements[ach.ach_kills_suicider_1, 0] = steam_get_stat_int("kills_suicider");	achievements[ach.ach_kills_suicider_1, 1] = "1 Suicider";	achievements[ach.ach_kills_suicider_1, 2] = "Destroy 1 Suicider";	achievements[ach.ach_kills_suicider_1, 3] = s_ach_enemies;	achievements[ach.ach_kills_suicider_1, 4] = 9;	achievements[ach.ach_kills_suicider_1, 5] = 8;	achievements[ach.ach_kills_suicider_1, 6] = 1;	achievements[ach.ach_kills_suicider_1, 7] = steam_get_achievement("ach_kills_suicider_1");
	achievements[ach.ach_kills_suicider_25, 0] = steam_get_stat_int("kills_suicider");	achievements[ach.ach_kills_suicider_25, 1] = "25 Suiciders";	achievements[ach.ach_kills_suicider_25, 2] = "Destroy 25 Suiciders";	achievements[ach.ach_kills_suicider_25, 3] = s_ach_enemies;	achievements[ach.ach_kills_suicider_25, 4] = 10;	achievements[ach.ach_kills_suicider_25, 5] = 8;	achievements[ach.ach_kills_suicider_25, 6] = 25;	achievements[ach.ach_kills_suicider_25, 7] = steam_get_achievement("ach_kills_suicider_25");
	achievements[ach.ach_kills_suicider_100, 0] = steam_get_stat_int("kills_suicider");	achievements[ach.ach_kills_suicider_100, 1] = "100 Suiciders";	achievements[ach.ach_kills_suicider_100, 2] = "Destroy 100 Suiciders";	achievements[ach.ach_kills_suicider_100, 3] = s_ach_enemies;	achievements[ach.ach_kills_suicider_100, 4] = 11;	achievements[ach.ach_kills_suicider_100, 5] = 8;	achievements[ach.ach_kills_suicider_100, 6] = 100;	achievements[ach.ach_kills_suicider_100, 7] = steam_get_achievement("ach_kills_suicider_100");
	achievements[ach.ach_kills_suicider_250, 0] = steam_get_stat_int("kills_suicider");	achievements[ach.ach_kills_suicider_250, 1] = "250 Suiciders";	achievements[ach.ach_kills_suicider_250, 2] = "Destroy 250 Suiciders";	achievements[ach.ach_kills_suicider_250, 3] = s_ach_enemies;	achievements[ach.ach_kills_suicider_250, 4] = 12;	achievements[ach.ach_kills_suicider_250, 5] = 8;	achievements[ach.ach_kills_suicider_250, 6] = 250;	achievements[ach.ach_kills_suicider_250, 7] = steam_get_achievement("ach_kills_suicider_250");
	achievements[ach.ach_kills_suicider_1000, 0] = steam_get_stat_int("kills_suicider");	achievements[ach.ach_kills_suicider_1000, 1] = "1,000 Suiciders";	achievements[ach.ach_kills_suicider_1000, 2] = "Destroy 1,000 Suiciders";	achievements[ach.ach_kills_suicider_1000, 3] = s_ach_enemies;	achievements[ach.ach_kills_suicider_1000, 4] = 13;	achievements[ach.ach_kills_suicider_1000, 5] = 8;	achievements[ach.ach_kills_suicider_1000, 6] = 1000;	achievements[ach.ach_kills_suicider_1000, 7] = steam_get_achievement("ach_kills_suicider_1000");
	achievements[ach.ach_kills_suicider_2500, 0] = steam_get_stat_int("kills_suicider");	achievements[ach.ach_kills_suicider_2500, 1] = "2,500 Suiciders";	achievements[ach.ach_kills_suicider_2500, 2] = "Destroy 2,500 Suiciders";	achievements[ach.ach_kills_suicider_2500, 3] = s_ach_enemies;	achievements[ach.ach_kills_suicider_2500, 4] = 14;	achievements[ach.ach_kills_suicider_2500, 5] = 8;	achievements[ach.ach_kills_suicider_2500, 6] = 2500;	achievements[ach.ach_kills_suicider_2500, 7] = steam_get_achievement("ach_kills_suicider_2500");
	achievements[ach.ach_kills_suicider_10000, 0] = steam_get_stat_int("kills_suicider");	achievements[ach.ach_kills_suicider_10000, 1] = "10,000 Suiciders";	achievements[ach.ach_kills_suicider_10000, 2] = "Destroy 10,000 Suiciders";	achievements[ach.ach_kills_suicider_10000, 3] = s_ach_enemies;	achievements[ach.ach_kills_suicider_10000, 4] = 15;	achievements[ach.ach_kills_suicider_10000, 5] = 8;	achievements[ach.ach_kills_suicider_10000, 6] = 10000;	achievements[ach.ach_kills_suicider_10000, 7] = steam_get_achievement("ach_kills_suicider_10000");
	achievements[ach.ach_kills_marauder_1, 0] = steam_get_stat_int("kills_marauder");	achievements[ach.ach_kills_marauder_1, 1] = "1 Marauder";	achievements[ach.ach_kills_marauder_1, 2] = "Destroy 1 Marauder";	achievements[ach.ach_kills_marauder_1, 3] = s_ach_enemies;	achievements[ach.ach_kills_marauder_1, 4] = 17;	achievements[ach.ach_kills_marauder_1, 5] = 16;	achievements[ach.ach_kills_marauder_1, 6] = 1;	achievements[ach.ach_kills_marauder_1, 7] = steam_get_achievement("ach_kills_marauder_1");
	achievements[ach.ach_kills_marauder_25, 0] = steam_get_stat_int("kills_marauder");	achievements[ach.ach_kills_marauder_25, 1] = "25 Marauders";	achievements[ach.ach_kills_marauder_25, 2] = "Destroy 25 Marauders";	achievements[ach.ach_kills_marauder_25, 3] = s_ach_enemies;	achievements[ach.ach_kills_marauder_25, 4] = 18;	achievements[ach.ach_kills_marauder_25, 5] = 16;	achievements[ach.ach_kills_marauder_25, 6] = 25;	achievements[ach.ach_kills_marauder_25, 7] = steam_get_achievement("ach_kills_marauder_25");
	achievements[ach.ach_kills_marauder_100, 0] = steam_get_stat_int("kills_marauder");	achievements[ach.ach_kills_marauder_100, 1] = "100 Marauders";	achievements[ach.ach_kills_marauder_100, 2] = "Destroy 100 Marauders";	achievements[ach.ach_kills_marauder_100, 3] = s_ach_enemies;	achievements[ach.ach_kills_marauder_100, 4] = 19;	achievements[ach.ach_kills_marauder_100, 5] = 16;	achievements[ach.ach_kills_marauder_100, 6] = 100;	achievements[ach.ach_kills_marauder_100, 7] = steam_get_achievement("ach_kills_marauder_100");
	achievements[ach.ach_kills_marauder_250, 0] = steam_get_stat_int("kills_marauder");	achievements[ach.ach_kills_marauder_250, 1] = "250 Marauders";	achievements[ach.ach_kills_marauder_250, 2] = "Destroy 250 Marauders";	achievements[ach.ach_kills_marauder_250, 3] = s_ach_enemies;	achievements[ach.ach_kills_marauder_250, 4] = 20;	achievements[ach.ach_kills_marauder_250, 5] = 16;	achievements[ach.ach_kills_marauder_250, 6] = 250;	achievements[ach.ach_kills_marauder_250, 7] = steam_get_achievement("ach_kills_marauder_250");
	achievements[ach.ach_kills_marauder_1000, 0] = steam_get_stat_int("kills_marauder");	achievements[ach.ach_kills_marauder_1000, 1] = "1,000 Marauders";	achievements[ach.ach_kills_marauder_1000, 2] = "Destroy 1,000 Marauders";	achievements[ach.ach_kills_marauder_1000, 3] = s_ach_enemies;	achievements[ach.ach_kills_marauder_1000, 4] = 21;	achievements[ach.ach_kills_marauder_1000, 5] = 16;	achievements[ach.ach_kills_marauder_1000, 6] = 1000;	achievements[ach.ach_kills_marauder_1000, 7] = steam_get_achievement("ach_kills_marauder_1000");
	achievements[ach.ach_kills_marauder_2500, 0] = steam_get_stat_int("kills_marauder");	achievements[ach.ach_kills_marauder_2500, 1] = "2,500 Marauders";	achievements[ach.ach_kills_marauder_2500, 2] = "Destroy 2,500 Marauders";	achievements[ach.ach_kills_marauder_2500, 3] = s_ach_enemies;	achievements[ach.ach_kills_marauder_2500, 4] = 22;	achievements[ach.ach_kills_marauder_2500, 5] = 16;	achievements[ach.ach_kills_marauder_2500, 6] = 2500;	achievements[ach.ach_kills_marauder_2500, 7] = steam_get_achievement("ach_kills_marauder_2500");
	achievements[ach.ach_kills_marauder_10000, 0] = steam_get_stat_int("kills_marauder");	achievements[ach.ach_kills_marauder_10000, 1] = "10,000 Marauders";	achievements[ach.ach_kills_marauder_10000, 2] = "Destroy 10,000 Marauders";	achievements[ach.ach_kills_marauder_10000, 3] = s_ach_enemies;	achievements[ach.ach_kills_marauder_10000, 4] = 23;	achievements[ach.ach_kills_marauder_10000, 5] = 16;	achievements[ach.ach_kills_marauder_10000, 6] = 10000;	achievements[ach.ach_kills_marauder_10000, 7] = steam_get_achievement("ach_kills_marauder_10000");
	achievements[ach.ach_kills_ion_1, 0] = steam_get_stat_int("kills_ion");	achievements[ach.ach_kills_ion_1, 1] = "1 Ion";	achievements[ach.ach_kills_ion_1, 2] = "Destroy 1 Ion";	achievements[ach.ach_kills_ion_1, 3] = s_ach_enemies;	achievements[ach.ach_kills_ion_1, 4] = 25;	achievements[ach.ach_kills_ion_1, 5] = 24;	achievements[ach.ach_kills_ion_1, 6] = 1;	achievements[ach.ach_kills_ion_1, 7] = steam_get_achievement("ach_kills_ion_1");
	achievements[ach.ach_kills_ion_25, 0] = steam_get_stat_int("kills_ion");	achievements[ach.ach_kills_ion_25, 1] = "25 Ions";	achievements[ach.ach_kills_ion_25, 2] = "Destroy 25 Ions";	achievements[ach.ach_kills_ion_25, 3] = s_ach_enemies;	achievements[ach.ach_kills_ion_25, 4] = 26;	achievements[ach.ach_kills_ion_25, 5] = 24;	achievements[ach.ach_kills_ion_25, 6] = 25;	achievements[ach.ach_kills_ion_25, 7] = steam_get_achievement("ach_kills_ion_25");
	achievements[ach.ach_kills_ion_100, 0] = steam_get_stat_int("kills_ion");	achievements[ach.ach_kills_ion_100, 1] = "100 Ions";	achievements[ach.ach_kills_ion_100, 2] = "Destroy 100 Ions";	achievements[ach.ach_kills_ion_100, 3] = s_ach_enemies;	achievements[ach.ach_kills_ion_100, 4] = 27;	achievements[ach.ach_kills_ion_100, 5] = 24;	achievements[ach.ach_kills_ion_100, 6] = 100;	achievements[ach.ach_kills_ion_100, 7] = steam_get_achievement("ach_kills_ion_100");
	achievements[ach.ach_kills_ion_250, 0] = steam_get_stat_int("kills_ion");	achievements[ach.ach_kills_ion_250, 1] = "250 Ions";	achievements[ach.ach_kills_ion_250, 2] = "Destroy 250 Ions";	achievements[ach.ach_kills_ion_250, 3] = s_ach_enemies;	achievements[ach.ach_kills_ion_250, 4] = 28;	achievements[ach.ach_kills_ion_250, 5] = 24;	achievements[ach.ach_kills_ion_250, 6] = 250;	achievements[ach.ach_kills_ion_250, 7] = steam_get_achievement("ach_kills_ion_250");
	achievements[ach.ach_kills_ion_1000, 0] = steam_get_stat_int("kills_ion");	achievements[ach.ach_kills_ion_1000, 1] = "1,000 Ions";	achievements[ach.ach_kills_ion_1000, 2] = "Destroy 1,000 Ions";	achievements[ach.ach_kills_ion_1000, 3] = s_ach_enemies;	achievements[ach.ach_kills_ion_1000, 4] = 29;	achievements[ach.ach_kills_ion_1000, 5] = 24;	achievements[ach.ach_kills_ion_1000, 6] = 1000;	achievements[ach.ach_kills_ion_1000, 7] = steam_get_achievement("ach_kills_ion_1000");
	achievements[ach.ach_kills_ion_2500, 0] = steam_get_stat_int("kills_ion");	achievements[ach.ach_kills_ion_2500, 1] = "2,500 Ions";	achievements[ach.ach_kills_ion_2500, 2] = "Destroy 2,500 Ions";	achievements[ach.ach_kills_ion_2500, 3] = s_ach_enemies;	achievements[ach.ach_kills_ion_2500, 4] = 30;	achievements[ach.ach_kills_ion_2500, 5] = 24;	achievements[ach.ach_kills_ion_2500, 6] = 2500;	achievements[ach.ach_kills_ion_2500, 7] = steam_get_achievement("ach_kills_ion_2500");
	achievements[ach.ach_kills_ion_10000, 0] = steam_get_stat_int("kills_ion");	achievements[ach.ach_kills_ion_10000, 1] = "10,000 Ions";	achievements[ach.ach_kills_ion_10000, 2] = "Destroy 10,000 Ions";	achievements[ach.ach_kills_ion_10000, 3] = s_ach_enemies;	achievements[ach.ach_kills_ion_10000, 4] = 31;	achievements[ach.ach_kills_ion_10000, 5] = 24;	achievements[ach.ach_kills_ion_10000, 6] = 10000;	achievements[ach.ach_kills_ion_10000, 7] = steam_get_achievement("ach_kills_ion_10000");
	achievements[ach.ach_kills_bomber_1, 0] = steam_get_stat_int("kills_bomber");	achievements[ach.ach_kills_bomber_1, 1] = "1 Bomber";	achievements[ach.ach_kills_bomber_1, 2] = "Destroy 1 Bomber";	achievements[ach.ach_kills_bomber_1, 3] = s_ach_enemies;	achievements[ach.ach_kills_bomber_1, 4] = 33;	achievements[ach.ach_kills_bomber_1, 5] = 32;	achievements[ach.ach_kills_bomber_1, 6] = 1;	achievements[ach.ach_kills_bomber_1, 7] = steam_get_achievement("ach_kills_bomber_1");
	achievements[ach.ach_kills_bomber_25, 0] = steam_get_stat_int("kills_bomber");	achievements[ach.ach_kills_bomber_25, 1] = "25 Bombers";	achievements[ach.ach_kills_bomber_25, 2] = "Destroy 25 Bombers";	achievements[ach.ach_kills_bomber_25, 3] = s_ach_enemies;	achievements[ach.ach_kills_bomber_25, 4] = 34;	achievements[ach.ach_kills_bomber_25, 5] = 32;	achievements[ach.ach_kills_bomber_25, 6] = 25;	achievements[ach.ach_kills_bomber_25, 7] = steam_get_achievement("ach_kills_bomber_25");
	achievements[ach.ach_kills_bomber_100, 0] = steam_get_stat_int("kills_bomber");	achievements[ach.ach_kills_bomber_100, 1] = "100 Bombers";	achievements[ach.ach_kills_bomber_100, 2] = "Destroy 100 Bombers";	achievements[ach.ach_kills_bomber_100, 3] = s_ach_enemies;	achievements[ach.ach_kills_bomber_100, 4] = 35;	achievements[ach.ach_kills_bomber_100, 5] = 32;	achievements[ach.ach_kills_bomber_100, 6] = 100;	achievements[ach.ach_kills_bomber_100, 7] = steam_get_achievement("ach_kills_bomber_100");
	achievements[ach.ach_kills_bomber_250, 0] = steam_get_stat_int("kills_bomber");	achievements[ach.ach_kills_bomber_250, 1] = "250 Bombers";	achievements[ach.ach_kills_bomber_250, 2] = "Destroy 250 Bombers";	achievements[ach.ach_kills_bomber_250, 3] = s_ach_enemies;	achievements[ach.ach_kills_bomber_250, 4] = 36;	achievements[ach.ach_kills_bomber_250, 5] = 32;	achievements[ach.ach_kills_bomber_250, 6] = 250;	achievements[ach.ach_kills_bomber_250, 7] = steam_get_achievement("ach_kills_bomber_250");
	achievements[ach.ach_kills_bomber_1000, 0] = steam_get_stat_int("kills_bomber");	achievements[ach.ach_kills_bomber_1000, 1] = "1,000 Bombers";	achievements[ach.ach_kills_bomber_1000, 2] = "Destroy 1,000 Bombers";	achievements[ach.ach_kills_bomber_1000, 3] = s_ach_enemies;	achievements[ach.ach_kills_bomber_1000, 4] = 37;	achievements[ach.ach_kills_bomber_1000, 5] = 32;	achievements[ach.ach_kills_bomber_1000, 6] = 1000;	achievements[ach.ach_kills_bomber_1000, 7] = steam_get_achievement("ach_kills_bomber_1000");
	achievements[ach.ach_kills_bomber_2500, 0] = steam_get_stat_int("kills_bomber");	achievements[ach.ach_kills_bomber_2500, 1] = "2,500 Bombers";	achievements[ach.ach_kills_bomber_2500, 2] = "Destroy 2,500 Bombers";	achievements[ach.ach_kills_bomber_2500, 3] = s_ach_enemies;	achievements[ach.ach_kills_bomber_2500, 4] = 38;	achievements[ach.ach_kills_bomber_2500, 5] = 32;	achievements[ach.ach_kills_bomber_2500, 6] = 2500;	achievements[ach.ach_kills_bomber_2500, 7] = steam_get_achievement("ach_kills_bomber_2500");
	achievements[ach.ach_kills_bomber_10000, 0] = steam_get_stat_int("kills_bomber");	achievements[ach.ach_kills_bomber_10000, 1] = "10,000 Bombers";	achievements[ach.ach_kills_bomber_10000, 2] = "Destroy 10,000 Bombers";	achievements[ach.ach_kills_bomber_10000, 3] = s_ach_enemies;	achievements[ach.ach_kills_bomber_10000, 4] = 39;	achievements[ach.ach_kills_bomber_10000, 5] = 32;	achievements[ach.ach_kills_bomber_10000, 6] = 10000;	achievements[ach.ach_kills_bomber_10000, 7] = steam_get_achievement("ach_kills_bomber_10000");
	achievements[ach.ach_kills_rusher_1, 0] = steam_get_stat_int("kills_rusher");	achievements[ach.ach_kills_rusher_1, 1] = "1 Rusher";	achievements[ach.ach_kills_rusher_1, 2] = "Destroy 1 Rusher";	achievements[ach.ach_kills_rusher_1, 3] = s_ach_enemies;	achievements[ach.ach_kills_rusher_1, 4] = 41;	achievements[ach.ach_kills_rusher_1, 5] = 40;	achievements[ach.ach_kills_rusher_1, 6] = 1;	achievements[ach.ach_kills_rusher_1, 7] = steam_get_achievement("ach_kills_rusher_1");
	achievements[ach.ach_kills_rusher_25, 0] = steam_get_stat_int("kills_rusher");	achievements[ach.ach_kills_rusher_25, 1] = "25 Rushers";	achievements[ach.ach_kills_rusher_25, 2] = "Destroy 25 Rushers";	achievements[ach.ach_kills_rusher_25, 3] = s_ach_enemies;	achievements[ach.ach_kills_rusher_25, 4] = 42;	achievements[ach.ach_kills_rusher_25, 5] = 40;	achievements[ach.ach_kills_rusher_25, 6] = 25;	achievements[ach.ach_kills_rusher_25, 7] = steam_get_achievement("ach_kills_rusher_25");
	achievements[ach.ach_kills_rusher_100, 0] = steam_get_stat_int("kills_rusher");	achievements[ach.ach_kills_rusher_100, 1] = "100 Rushers";	achievements[ach.ach_kills_rusher_100, 2] = "Destroy 100 Rushers";	achievements[ach.ach_kills_rusher_100, 3] = s_ach_enemies;	achievements[ach.ach_kills_rusher_100, 4] = 43;	achievements[ach.ach_kills_rusher_100, 5] = 40;	achievements[ach.ach_kills_rusher_100, 6] = 100;	achievements[ach.ach_kills_rusher_100, 7] = steam_get_achievement("ach_kills_rusher_100");
	achievements[ach.ach_kills_rusher_250, 0] = steam_get_stat_int("kills_rusher");	achievements[ach.ach_kills_rusher_250, 1] = "250 Rushers";	achievements[ach.ach_kills_rusher_250, 2] = "Destroy 250 Rushers";	achievements[ach.ach_kills_rusher_250, 3] = s_ach_enemies;	achievements[ach.ach_kills_rusher_250, 4] = 44;	achievements[ach.ach_kills_rusher_250, 5] = 40;	achievements[ach.ach_kills_rusher_250, 6] = 250;	achievements[ach.ach_kills_rusher_250, 7] = steam_get_achievement("ach_kills_rusher_250");
	achievements[ach.ach_kills_rusher_1000, 0] = steam_get_stat_int("kills_rusher");	achievements[ach.ach_kills_rusher_1000, 1] = "1,000 Rushers";	achievements[ach.ach_kills_rusher_1000, 2] = "Destroy 1,000 Rushers";	achievements[ach.ach_kills_rusher_1000, 3] = s_ach_enemies;	achievements[ach.ach_kills_rusher_1000, 4] = 45;	achievements[ach.ach_kills_rusher_1000, 5] = 40;	achievements[ach.ach_kills_rusher_1000, 6] = 1000;	achievements[ach.ach_kills_rusher_1000, 7] = steam_get_achievement("ach_kills_rusher_1000");
	achievements[ach.ach_kills_rusher_2500, 0] = steam_get_stat_int("kills_rusher");	achievements[ach.ach_kills_rusher_2500, 1] = "2,500 Rushers";	achievements[ach.ach_kills_rusher_2500, 2] = "Destroy 2,500 Rushers";	achievements[ach.ach_kills_rusher_2500, 3] = s_ach_enemies;	achievements[ach.ach_kills_rusher_2500, 4] = 46;	achievements[ach.ach_kills_rusher_2500, 5] = 40;	achievements[ach.ach_kills_rusher_2500, 6] = 2500;	achievements[ach.ach_kills_rusher_2500, 7] = steam_get_achievement("ach_kills_rusher_2500");
	achievements[ach.ach_kills_rusher_10000, 0] = steam_get_stat_int("kills_rusher");	achievements[ach.ach_kills_rusher_10000, 1] = "10,000 Rushers";	achievements[ach.ach_kills_rusher_10000, 2] = "Destroy 10,000 Rushers";	achievements[ach.ach_kills_rusher_10000, 3] = s_ach_enemies;	achievements[ach.ach_kills_rusher_10000, 4] = 47;	achievements[ach.ach_kills_rusher_10000, 5] = 40;	achievements[ach.ach_kills_rusher_10000, 6] = 10000;	achievements[ach.ach_kills_rusher_10000, 7] = steam_get_achievement("ach_kills_rusher_10000");
	achievements[ach.ach_kills_ranger_1, 0] = steam_get_stat_int("kills_sniper");	achievements[ach.ach_kills_ranger_1, 1] = "1 Sniper";	achievements[ach.ach_kills_ranger_1, 2] = "Destroy 1 Sniper";	achievements[ach.ach_kills_ranger_1, 3] = s_ach_enemies;	achievements[ach.ach_kills_ranger_1, 4] = 49;	achievements[ach.ach_kills_ranger_1, 5] = 48;	achievements[ach.ach_kills_ranger_1, 6] = 1;	achievements[ach.ach_kills_ranger_1, 7] = steam_get_achievement("ach_kills_ranger_1");
	achievements[ach.ach_kills_ranger_25, 0] = steam_get_stat_int("kills_sniper");	achievements[ach.ach_kills_ranger_25, 1] = "25 Snipers";	achievements[ach.ach_kills_ranger_25, 2] = "Destroy 25 Snipers";	achievements[ach.ach_kills_ranger_25, 3] = s_ach_enemies;	achievements[ach.ach_kills_ranger_25, 4] = 50;	achievements[ach.ach_kills_ranger_25, 5] = 48;	achievements[ach.ach_kills_ranger_25, 6] = 25;	achievements[ach.ach_kills_ranger_25, 7] = steam_get_achievement("ach_kills_ranger_25");
	achievements[ach.ach_kills_ranger_100, 0] = steam_get_stat_int("kills_sniper");	achievements[ach.ach_kills_ranger_100, 1] = "100 Snipers";	achievements[ach.ach_kills_ranger_100, 2] = "Destroy 100 Snipers";	achievements[ach.ach_kills_ranger_100, 3] = s_ach_enemies;	achievements[ach.ach_kills_ranger_100, 4] = 51;	achievements[ach.ach_kills_ranger_100, 5] = 48;	achievements[ach.ach_kills_ranger_100, 6] = 100;	achievements[ach.ach_kills_ranger_100, 7] = steam_get_achievement("ach_kills_ranger_100");
	achievements[ach.ach_kills_ranger_250, 0] = steam_get_stat_int("kills_sniper");	achievements[ach.ach_kills_ranger_250, 1] = "250 Snipers";	achievements[ach.ach_kills_ranger_250, 2] = "Destroy 250 Snipers";	achievements[ach.ach_kills_ranger_250, 3] = s_ach_enemies;	achievements[ach.ach_kills_ranger_250, 4] = 52;	achievements[ach.ach_kills_ranger_250, 5] = 48;	achievements[ach.ach_kills_ranger_250, 6] = 250;	achievements[ach.ach_kills_ranger_250, 7] = steam_get_achievement("ach_kills_ranger_250");
	achievements[ach.ach_kills_ranger_1000, 0] = steam_get_stat_int("kills_sniper");	achievements[ach.ach_kills_ranger_1000, 1] = "1,000 Snipers";	achievements[ach.ach_kills_ranger_1000, 2] = "Destroy 1,000 Snipers";	achievements[ach.ach_kills_ranger_1000, 3] = s_ach_enemies;	achievements[ach.ach_kills_ranger_1000, 4] = 53;	achievements[ach.ach_kills_ranger_1000, 5] = 48;	achievements[ach.ach_kills_ranger_1000, 6] = 1000;	achievements[ach.ach_kills_ranger_1000, 7] = steam_get_achievement("ach_kills_ranger_1000");
	achievements[ach.ach_kills_ranger_2500, 0] = steam_get_stat_int("kills_sniper");	achievements[ach.ach_kills_ranger_2500, 1] = "2,500 Snipers";	achievements[ach.ach_kills_ranger_2500, 2] = "Destroy 2,500 Snipers";	achievements[ach.ach_kills_ranger_2500, 3] = s_ach_enemies;	achievements[ach.ach_kills_ranger_2500, 4] = 54;	achievements[ach.ach_kills_ranger_2500, 5] = 48;	achievements[ach.ach_kills_ranger_2500, 6] = 2500;	achievements[ach.ach_kills_ranger_2500, 7] = steam_get_achievement("ach_kills_ranger_2500");
	achievements[ach.ach_kills_ranger_10000, 0] = steam_get_stat_int("kills_sniper");	achievements[ach.ach_kills_ranger_10000, 1] = "10,000 Snipers";	achievements[ach.ach_kills_ranger_10000, 2] = "Destroy 10,000 Snipers";	achievements[ach.ach_kills_ranger_10000, 3] = s_ach_enemies;	achievements[ach.ach_kills_ranger_10000, 4] = 55;	achievements[ach.ach_kills_ranger_10000, 5] = 48;	achievements[ach.ach_kills_ranger_10000, 6] = 10000;	achievements[ach.ach_kills_ranger_10000, 7] = steam_get_achievement("ach_kills_ranger_10000");
	achievements[ach.ach_kills_gunship_1, 0] = steam_get_stat_int("kills_gunship");	achievements[ach.ach_kills_gunship_1, 1] = "1 Gunship";	achievements[ach.ach_kills_gunship_1, 2] = "Destroy 1 Gunship";	achievements[ach.ach_kills_gunship_1, 3] = s_ach_enemies;	achievements[ach.ach_kills_gunship_1, 4] = 57;	achievements[ach.ach_kills_gunship_1, 5] = 56;	achievements[ach.ach_kills_gunship_1, 6] = 1;	achievements[ach.ach_kills_gunship_1, 7] = steam_get_achievement("ach_kills_gunship_1");
	achievements[ach.ach_kills_gunship_25, 0] = steam_get_stat_int("kills_gunship");	achievements[ach.ach_kills_gunship_25, 1] = "25 Gunships";	achievements[ach.ach_kills_gunship_25, 2] = "Destroy 25 Gunships";	achievements[ach.ach_kills_gunship_25, 3] = s_ach_enemies;	achievements[ach.ach_kills_gunship_25, 4] = 58;	achievements[ach.ach_kills_gunship_25, 5] = 56;	achievements[ach.ach_kills_gunship_25, 6] = 25;	achievements[ach.ach_kills_gunship_25, 7] = steam_get_achievement("ach_kills_gunship_25");
	achievements[ach.ach_kills_gunship_100, 0] = steam_get_stat_int("kills_gunship");	achievements[ach.ach_kills_gunship_100, 1] = "100 Gunships";	achievements[ach.ach_kills_gunship_100, 2] = "Destroy 100 Gunships";	achievements[ach.ach_kills_gunship_100, 3] = s_ach_enemies;	achievements[ach.ach_kills_gunship_100, 4] = 59;	achievements[ach.ach_kills_gunship_100, 5] = 56;	achievements[ach.ach_kills_gunship_100, 6] = 100;	achievements[ach.ach_kills_gunship_100, 7] = steam_get_achievement("ach_kills_gunship_100");
	achievements[ach.ach_kills_gunship_250, 0] = steam_get_stat_int("kills_gunship");	achievements[ach.ach_kills_gunship_250, 1] = "250 Gunships";	achievements[ach.ach_kills_gunship_250, 2] = "Destroy 250 Gunships";	achievements[ach.ach_kills_gunship_250, 3] = s_ach_enemies;	achievements[ach.ach_kills_gunship_250, 4] = 60;	achievements[ach.ach_kills_gunship_250, 5] = 56;	achievements[ach.ach_kills_gunship_250, 6] = 250;	achievements[ach.ach_kills_gunship_250, 7] = steam_get_achievement("ach_kills_gunship_250");
	achievements[ach.ach_kills_gunship_1000, 0] = steam_get_stat_int("kills_gunship");	achievements[ach.ach_kills_gunship_1000, 1] = "1,000 Gunships";	achievements[ach.ach_kills_gunship_1000, 2] = "Destroy 1,000 Gunships";	achievements[ach.ach_kills_gunship_1000, 3] = s_ach_enemies;	achievements[ach.ach_kills_gunship_1000, 4] = 61;	achievements[ach.ach_kills_gunship_1000, 5] = 56;	achievements[ach.ach_kills_gunship_1000, 6] = 1000;	achievements[ach.ach_kills_gunship_1000, 7] = steam_get_achievement("ach_kills_gunship_1000");
	achievements[ach.ach_kills_gunship_2500, 0] = steam_get_stat_int("kills_gunship");	achievements[ach.ach_kills_gunship_2500, 1] = "2,500 Gunships";	achievements[ach.ach_kills_gunship_2500, 2] = "Destroy 2,500 Gunships";	achievements[ach.ach_kills_gunship_2500, 3] = s_ach_enemies;	achievements[ach.ach_kills_gunship_2500, 4] = 62;	achievements[ach.ach_kills_gunship_2500, 5] = 56;	achievements[ach.ach_kills_gunship_2500, 6] = 2500;	achievements[ach.ach_kills_gunship_2500, 7] = steam_get_achievement("ach_kills_gunship_2500");
	achievements[ach.ach_kills_gunship_10000, 0] = steam_get_stat_int("kills_gunship");	achievements[ach.ach_kills_gunship_10000, 1] = "10,000 Gunships";	achievements[ach.ach_kills_gunship_10000, 2] = "Destroy 10,000 Gunships";	achievements[ach.ach_kills_gunship_10000, 3] = s_ach_enemies;	achievements[ach.ach_kills_gunship_10000, 4] = 63;	achievements[ach.ach_kills_gunship_10000, 5] = 56;	achievements[ach.ach_kills_gunship_10000, 6] = 10000;	achievements[ach.ach_kills_gunship_10000, 7] = steam_get_achievement("ach_kills_gunship_10000");
	achievements[ach.ach_kills_destroyer_1, 0] = steam_get_stat_int("kills_destroyer");	achievements[ach.ach_kills_destroyer_1, 1] = "1 Destroyer";	achievements[ach.ach_kills_destroyer_1, 2] = "Destroy 1 Destroyer";	achievements[ach.ach_kills_destroyer_1, 3] = s_ach_enemies;	achievements[ach.ach_kills_destroyer_1, 4] = 65;	achievements[ach.ach_kills_destroyer_1, 5] = 64;	achievements[ach.ach_kills_destroyer_1, 6] = 1;	achievements[ach.ach_kills_destroyer_1, 7] = steam_get_achievement("ach_kills_destroyer_1");
	achievements[ach.ach_kills_destroyer_25, 0] = steam_get_stat_int("kills_destroyer");	achievements[ach.ach_kills_destroyer_25, 1] = "25 Destroyers";	achievements[ach.ach_kills_destroyer_25, 2] = "Destroy 25 Destroyers";	achievements[ach.ach_kills_destroyer_25, 3] = s_ach_enemies;	achievements[ach.ach_kills_destroyer_25, 4] = 66;	achievements[ach.ach_kills_destroyer_25, 5] = 64;	achievements[ach.ach_kills_destroyer_25, 6] = 25;	achievements[ach.ach_kills_destroyer_25, 7] = steam_get_achievement("ach_kills_destroyer_25");
	achievements[ach.ach_kills_destroyer_100, 0] = steam_get_stat_int("kills_destroyer");	achievements[ach.ach_kills_destroyer_100, 1] = "100 Destroyers";	achievements[ach.ach_kills_destroyer_100, 2] = "Destroy 100 Destroyers";	achievements[ach.ach_kills_destroyer_100, 3] = s_ach_enemies;	achievements[ach.ach_kills_destroyer_100, 4] = 67;	achievements[ach.ach_kills_destroyer_100, 5] = 64;	achievements[ach.ach_kills_destroyer_100, 6] = 100;	achievements[ach.ach_kills_destroyer_100, 7] = steam_get_achievement("ach_kills_destroyer_100");
	achievements[ach.ach_kills_destroyer_250, 0] = steam_get_stat_int("kills_destroyer");	achievements[ach.ach_kills_destroyer_250, 1] = "250 Destroyers";	achievements[ach.ach_kills_destroyer_250, 2] = "Destroy 250 Destroyers";	achievements[ach.ach_kills_destroyer_250, 3] = s_ach_enemies;	achievements[ach.ach_kills_destroyer_250, 4] = 68;	achievements[ach.ach_kills_destroyer_250, 5] = 64;	achievements[ach.ach_kills_destroyer_250, 6] = 250;	achievements[ach.ach_kills_destroyer_250, 7] = steam_get_achievement("ach_kills_destroyer_250");
	achievements[ach.ach_kills_destroyer_1000, 0] = steam_get_stat_int("kills_destroyer");	achievements[ach.ach_kills_destroyer_1000, 1] = "1,000 Destroyers";	achievements[ach.ach_kills_destroyer_1000, 2] = "Destroy 1,000 Destroyers";	achievements[ach.ach_kills_destroyer_1000, 3] = s_ach_enemies;	achievements[ach.ach_kills_destroyer_1000, 4] = 69;	achievements[ach.ach_kills_destroyer_1000, 5] = 64;	achievements[ach.ach_kills_destroyer_1000, 6] = 1000;	achievements[ach.ach_kills_destroyer_1000, 7] = steam_get_achievement("ach_kills_destroyer_1000");
	achievements[ach.ach_kills_destroyer_2500, 0] = steam_get_stat_int("kills_destroyer");	achievements[ach.ach_kills_destroyer_2500, 1] = "2,500 Destroyers";	achievements[ach.ach_kills_destroyer_2500, 2] = "Destroy 2,500 Destroyers";	achievements[ach.ach_kills_destroyer_2500, 3] = s_ach_enemies;	achievements[ach.ach_kills_destroyer_2500, 4] = 70;	achievements[ach.ach_kills_destroyer_2500, 5] = 64;	achievements[ach.ach_kills_destroyer_2500, 6] = 2500;	achievements[ach.ach_kills_destroyer_2500, 7] = steam_get_achievement("ach_kills_destroyer_2500");
	achievements[ach.ach_kills_destroyer_10000, 0] = steam_get_stat_int("kills_destroyer");	achievements[ach.ach_kills_destroyer_10000, 1] = "10,000 Destroyers";	achievements[ach.ach_kills_destroyer_10000, 2] = "Destroy 10,000 Destroyers";	achievements[ach.ach_kills_destroyer_10000, 3] = s_ach_enemies;	achievements[ach.ach_kills_destroyer_10000, 4] = 71;	achievements[ach.ach_kills_destroyer_10000, 5] = 64;	achievements[ach.ach_kills_destroyer_10000, 6] = 10000;	achievements[ach.ach_kills_destroyer_10000, 7] = steam_get_achievement("ach_kills_destroyer_10000");
	achievements[ach.ach_kills_shotgunner_1, 0] = steam_get_stat_int("kills_shotgunner");	achievements[ach.ach_kills_shotgunner_1, 1] = "1 Shotgunner";	achievements[ach.ach_kills_shotgunner_1, 2] = "Destroy 1 Shotgunner";	achievements[ach.ach_kills_shotgunner_1, 3] = s_ach_enemies;	achievements[ach.ach_kills_shotgunner_1, 4] = 73;	achievements[ach.ach_kills_shotgunner_1, 5] = 72;	achievements[ach.ach_kills_shotgunner_1, 6] = 1;	achievements[ach.ach_kills_shotgunner_1, 7] = steam_get_achievement("ach_kills_shotgunner_1");
	achievements[ach.ach_kills_shotgunner_25, 0] = steam_get_stat_int("kills_shotgunner");	achievements[ach.ach_kills_shotgunner_25, 1] = "25 Shotgunners";	achievements[ach.ach_kills_shotgunner_25, 2] = "Destroy 25 Shotgunners";	achievements[ach.ach_kills_shotgunner_25, 3] = s_ach_enemies;	achievements[ach.ach_kills_shotgunner_25, 4] = 74;	achievements[ach.ach_kills_shotgunner_25, 5] = 72;	achievements[ach.ach_kills_shotgunner_25, 6] = 25;	achievements[ach.ach_kills_shotgunner_25, 7] = steam_get_achievement("ach_kills_shotgunner_25");
	achievements[ach.ach_kills_shotgunner_100, 0] = steam_get_stat_int("kills_shotgunner");	achievements[ach.ach_kills_shotgunner_100, 1] = "100 Shotgunners";	achievements[ach.ach_kills_shotgunner_100, 2] = "Destroy 100 Shotgunners";	achievements[ach.ach_kills_shotgunner_100, 3] = s_ach_enemies;	achievements[ach.ach_kills_shotgunner_100, 4] = 75;	achievements[ach.ach_kills_shotgunner_100, 5] = 72;	achievements[ach.ach_kills_shotgunner_100, 6] = 100;	achievements[ach.ach_kills_shotgunner_100, 7] = steam_get_achievement("ach_kills_shotgunner_100");
	achievements[ach.ach_kills_shotgunner_250, 0] = steam_get_stat_int("kills_shotgunner");	achievements[ach.ach_kills_shotgunner_250, 1] = "250 Shotgunners";	achievements[ach.ach_kills_shotgunner_250, 2] = "Destroy 250 Shotgunners";	achievements[ach.ach_kills_shotgunner_250, 3] = s_ach_enemies;	achievements[ach.ach_kills_shotgunner_250, 4] = 76;	achievements[ach.ach_kills_shotgunner_250, 5] = 72;	achievements[ach.ach_kills_shotgunner_250, 6] = 250;	achievements[ach.ach_kills_shotgunner_250, 7] = steam_get_achievement("ach_kills_shotgunner_250");
	achievements[ach.ach_kills_shotgunner_1000, 0] = steam_get_stat_int("kills_shotgunner");	achievements[ach.ach_kills_shotgunner_1000, 1] = "1,000 Shotgunners";	achievements[ach.ach_kills_shotgunner_1000, 2] = "Destroy 1,000 Shotgunners";	achievements[ach.ach_kills_shotgunner_1000, 3] = s_ach_enemies;	achievements[ach.ach_kills_shotgunner_1000, 4] = 77;	achievements[ach.ach_kills_shotgunner_1000, 5] = 72;	achievements[ach.ach_kills_shotgunner_1000, 6] = 1000;	achievements[ach.ach_kills_shotgunner_1000, 7] = steam_get_achievement("ach_kills_shotgunner_1000");
	achievements[ach.ach_kills_shotgunner_2500, 0] = steam_get_stat_int("kills_shotgunner");	achievements[ach.ach_kills_shotgunner_2500, 1] = "2,500 Shotgunners";	achievements[ach.ach_kills_shotgunner_2500, 2] = "Destroy 2,500 Shotgunners";	achievements[ach.ach_kills_shotgunner_2500, 3] = s_ach_enemies;	achievements[ach.ach_kills_shotgunner_2500, 4] = 78;	achievements[ach.ach_kills_shotgunner_2500, 5] = 72;	achievements[ach.ach_kills_shotgunner_2500, 6] = 2500;	achievements[ach.ach_kills_shotgunner_2500, 7] = steam_get_achievement("ach_kills_shotgunner_2500");
	achievements[ach.ach_kills_shotgunner_10000, 0] = steam_get_stat_int("kills_shotgunner");	achievements[ach.ach_kills_shotgunner_10000, 1] = "10,000 Shotgunners";	achievements[ach.ach_kills_shotgunner_10000, 2] = "Destroy 10,000 Shotgunners";	achievements[ach.ach_kills_shotgunner_10000, 3] = s_ach_enemies;	achievements[ach.ach_kills_shotgunner_10000, 4] = 79;	achievements[ach.ach_kills_shotgunner_10000, 5] = 72;	achievements[ach.ach_kills_shotgunner_10000, 6] = 10000;	achievements[ach.ach_kills_shotgunner_10000, 7] = steam_get_achievement("ach_kills_shotgunner_10000");
	achievements[ach.ach_kills_swarmer_1, 0] = steam_get_stat_int("kills_swarmer");	achievements[ach.ach_kills_swarmer_1, 1] = "1 Swarmer";	achievements[ach.ach_kills_swarmer_1, 2] = "Destroy 1 Swarmer";	achievements[ach.ach_kills_swarmer_1, 3] = s_ach_enemies;	achievements[ach.ach_kills_swarmer_1, 4] = 81;	achievements[ach.ach_kills_swarmer_1, 5] = 80;	achievements[ach.ach_kills_swarmer_1, 6] = 1;	achievements[ach.ach_kills_swarmer_1, 7] = steam_get_achievement("ach_kills_swarmer_1");
	achievements[ach.ach_kills_swarmer_25, 0] = steam_get_stat_int("kills_swarmer");	achievements[ach.ach_kills_swarmer_25, 1] = "25 Swarmers";	achievements[ach.ach_kills_swarmer_25, 2] = "Destroy 25 Swarmers";	achievements[ach.ach_kills_swarmer_25, 3] = s_ach_enemies;	achievements[ach.ach_kills_swarmer_25, 4] = 82;	achievements[ach.ach_kills_swarmer_25, 5] = 80;	achievements[ach.ach_kills_swarmer_25, 6] = 25;	achievements[ach.ach_kills_swarmer_25, 7] = steam_get_achievement("ach_kills_swarmer_25");
	achievements[ach.ach_kills_swarmer_100, 0] = steam_get_stat_int("kills_swarmer");	achievements[ach.ach_kills_swarmer_100, 1] = "100 Swarmers";	achievements[ach.ach_kills_swarmer_100, 2] = "Destroy 100 Swarmers";	achievements[ach.ach_kills_swarmer_100, 3] = s_ach_enemies;	achievements[ach.ach_kills_swarmer_100, 4] = 83;	achievements[ach.ach_kills_swarmer_100, 5] = 80;	achievements[ach.ach_kills_swarmer_100, 6] = 100;	achievements[ach.ach_kills_swarmer_100, 7] = steam_get_achievement("ach_kills_swarmer_100");
	achievements[ach.ach_kills_swarmer_250, 0] = steam_get_stat_int("kills_swarmer");	achievements[ach.ach_kills_swarmer_250, 1] = "250 Swarmers";	achievements[ach.ach_kills_swarmer_250, 2] = "Destroy 250 Swarmers";	achievements[ach.ach_kills_swarmer_250, 3] = s_ach_enemies;	achievements[ach.ach_kills_swarmer_250, 4] = 84;	achievements[ach.ach_kills_swarmer_250, 5] = 80;	achievements[ach.ach_kills_swarmer_250, 6] = 250;	achievements[ach.ach_kills_swarmer_250, 7] = steam_get_achievement("ach_kills_swarmer_250");
	achievements[ach.ach_kills_swarmer_1000, 0] = steam_get_stat_int("kills_swarmer");	achievements[ach.ach_kills_swarmer_1000, 1] = "1,000 Swarmers";	achievements[ach.ach_kills_swarmer_1000, 2] = "Destroy 1,000 Swarmers";	achievements[ach.ach_kills_swarmer_1000, 3] = s_ach_enemies;	achievements[ach.ach_kills_swarmer_1000, 4] = 85;	achievements[ach.ach_kills_swarmer_1000, 5] = 80;	achievements[ach.ach_kills_swarmer_1000, 6] = 1000;	achievements[ach.ach_kills_swarmer_1000, 7] = steam_get_achievement("ach_kills_swarmer_1000");
	achievements[ach.ach_kills_swarmer_2500, 0] = steam_get_stat_int("kills_swarmer");	achievements[ach.ach_kills_swarmer_2500, 1] = "2,500 Swarmers";	achievements[ach.ach_kills_swarmer_2500, 2] = "Destroy 2,500 Swarmers";	achievements[ach.ach_kills_swarmer_2500, 3] = s_ach_enemies;	achievements[ach.ach_kills_swarmer_2500, 4] = 86;	achievements[ach.ach_kills_swarmer_2500, 5] = 80;	achievements[ach.ach_kills_swarmer_2500, 6] = 2500;	achievements[ach.ach_kills_swarmer_2500, 7] = steam_get_achievement("ach_kills_swarmer_2500");
	achievements[ach.ach_kills_swarmer_10000, 0] = steam_get_stat_int("kills_swarmer");	achievements[ach.ach_kills_swarmer_10000, 1] = "10,000 Swarmers";	achievements[ach.ach_kills_swarmer_10000, 2] = "Destroy 10,000 Swarmers";	achievements[ach.ach_kills_swarmer_10000, 3] = s_ach_enemies;	achievements[ach.ach_kills_swarmer_10000, 4] = 87;	achievements[ach.ach_kills_swarmer_10000, 5] = 80;	achievements[ach.ach_kills_swarmer_10000, 6] = 10000;	achievements[ach.ach_kills_swarmer_10000, 7] = steam_get_achievement("ach_kills_swarmer_10000");
	achievements[ach.ach_kills_heavy_cruiser_1, 0] = steam_get_stat_int("kills_heavy_cruiser");	achievements[ach.ach_kills_heavy_cruiser_1, 1] = "1 Heavy Cruiser";	achievements[ach.ach_kills_heavy_cruiser_1, 2] = "Destroy 1 Heavy Cruiser";	achievements[ach.ach_kills_heavy_cruiser_1, 3] = s_ach_enemies;	achievements[ach.ach_kills_heavy_cruiser_1, 4] = 89;	achievements[ach.ach_kills_heavy_cruiser_1, 5] = 88;	achievements[ach.ach_kills_heavy_cruiser_1, 6] = 1;	achievements[ach.ach_kills_heavy_cruiser_1, 7] = steam_get_achievement("ach_kills_heavy_cruiser_1");
	achievements[ach.ach_kills_heavy_cruiser_25, 0] = steam_get_stat_int("kills_heavy_cruiser");	achievements[ach.ach_kills_heavy_cruiser_25, 1] = "25 Heavy Cruisers";	achievements[ach.ach_kills_heavy_cruiser_25, 2] = "Destroy 25 Heavy Cruisers";	achievements[ach.ach_kills_heavy_cruiser_25, 3] = s_ach_enemies;	achievements[ach.ach_kills_heavy_cruiser_25, 4] = 90;	achievements[ach.ach_kills_heavy_cruiser_25, 5] = 88;	achievements[ach.ach_kills_heavy_cruiser_25, 6] = 25;	achievements[ach.ach_kills_heavy_cruiser_25, 7] = steam_get_achievement("ach_kills_heavy_cruiser_25");
	achievements[ach.ach_kills_heavy_cruiser_100, 0] = steam_get_stat_int("kills_heavy_cruiser");	achievements[ach.ach_kills_heavy_cruiser_100, 1] = "100 Heavy Cruisers";	achievements[ach.ach_kills_heavy_cruiser_100, 2] = "Destroy 100 Heavy Cruisers";	achievements[ach.ach_kills_heavy_cruiser_100, 3] = s_ach_enemies;	achievements[ach.ach_kills_heavy_cruiser_100, 4] = 91;	achievements[ach.ach_kills_heavy_cruiser_100, 5] = 88;	achievements[ach.ach_kills_heavy_cruiser_100, 6] = 100;	achievements[ach.ach_kills_heavy_cruiser_100, 7] = steam_get_achievement("ach_kills_heavy_cruiser_100");
	achievements[ach.ach_kills_battlecruiser_1, 0] = steam_get_stat_int("kills_battlecruiser");	achievements[ach.ach_kills_battlecruiser_1, 1] = "1 Battlecruiser";	achievements[ach.ach_kills_battlecruiser_1, 2] = "Destroy 1 Battlecruiser";	achievements[ach.ach_kills_battlecruiser_1, 3] = s_ach_enemies;	achievements[ach.ach_kills_battlecruiser_1, 4] = 93;	achievements[ach.ach_kills_battlecruiser_1, 5] = 92;	achievements[ach.ach_kills_battlecruiser_1, 6] = 1;	achievements[ach.ach_kills_battlecruiser_1, 7] = steam_get_achievement("ach_kills_battlecruiser_1");
	achievements[ach.ach_kills_battlecruiser_10, 0] = steam_get_stat_int("kills_battlecruiser");	achievements[ach.ach_kills_battlecruiser_10, 1] = "10 Battlecruisers";	achievements[ach.ach_kills_battlecruiser_10, 2] = "Destroy 10 Battlecruisers";	achievements[ach.ach_kills_battlecruiser_10, 3] = s_ach_enemies;	achievements[ach.ach_kills_battlecruiser_10, 4] = 94;	achievements[ach.ach_kills_battlecruiser_10, 5] = 92;	achievements[ach.ach_kills_battlecruiser_10, 6] = 25;	achievements[ach.ach_kills_battlecruiser_10, 7] = steam_get_achievement("ach_kills_battlecruiser_10");
	achievements[ach.ach_kills_battlecruiser_25, 0] = steam_get_stat_int("kills_battlecruiser");	achievements[ach.ach_kills_battlecruiser_25, 1] = "25 Battlecruisers";	achievements[ach.ach_kills_battlecruiser_25, 2] = "Destroy 25 Battlecruisers";	achievements[ach.ach_kills_battlecruiser_25, 3] = s_ach_enemies;	achievements[ach.ach_kills_battlecruiser_25, 4] = 95;	achievements[ach.ach_kills_battlecruiser_25, 5] = 92;	achievements[ach.ach_kills_battlecruiser_25, 6] = 100;	achievements[ach.ach_kills_battlecruiser_25, 7] = steam_get_achievement("ach_kills_battlecruiser_25");
	achievements[ach.ach_wave_1, 0] = steam_get_stat_int("highest_wave");	achievements[ach.ach_wave_1, 1] = "Wave 1";	achievements[ach.ach_wave_1, 2] = "Beat Wave 1";	achievements[ach.ach_wave_1, 3] = s_ach_wave;	achievements[ach.ach_wave_1, 4] = 0;	achievements[ach.ach_wave_1, 5] = 1;	achievements[ach.ach_wave_1, 6] = 1;	achievements[ach.ach_wave_1, 7] = steam_get_achievement("ach_wave_1");
	achievements[ach.ach_wave_5, 0] = steam_get_stat_int("highest_wave");	achievements[ach.ach_wave_5, 1] = "Wave 5";	achievements[ach.ach_wave_5, 2] = "Beat Wave 5";	achievements[ach.ach_wave_5, 3] = s_ach_wave;	achievements[ach.ach_wave_5, 4] = 2;	achievements[ach.ach_wave_5, 5] = 3;	achievements[ach.ach_wave_5, 6] = 5;	achievements[ach.ach_wave_5, 7] = steam_get_achievement("ach_wave_5");
	achievements[ach.ach_wave_10, 0] = steam_get_stat_int("highest_wave");	achievements[ach.ach_wave_10, 1] = "Wave 10";	achievements[ach.ach_wave_10, 2] = "Beat Wave 10";	achievements[ach.ach_wave_10, 3] = s_ach_wave;	achievements[ach.ach_wave_10, 4] = 4;	achievements[ach.ach_wave_10, 5] = 5;	achievements[ach.ach_wave_10, 6] = 10;	achievements[ach.ach_wave_10, 7] = steam_get_achievement("ach_wave_10");
	achievements[ach.ach_wave_25, 0] = steam_get_stat_int("highest_wave");	achievements[ach.ach_wave_25, 1] = "Wave 25";	achievements[ach.ach_wave_25, 2] = "Beat Wave 25";	achievements[ach.ach_wave_25, 3] = s_ach_wave;	achievements[ach.ach_wave_25, 4] = 6;	achievements[ach.ach_wave_25, 5] = 7;	achievements[ach.ach_wave_25, 6] = 25;	achievements[ach.ach_wave_25, 7] = steam_get_achievement("ach_wave_25");
	achievements[ach.ach_wave_50, 0] = steam_get_stat_int("highest_wave");	achievements[ach.ach_wave_50, 1] = "Wave 50";	achievements[ach.ach_wave_50, 2] = "Beat Wave 50";	achievements[ach.ach_wave_50, 3] = s_ach_wave;	achievements[ach.ach_wave_50, 4] = 8;	achievements[ach.ach_wave_50, 5] = 9;	achievements[ach.ach_wave_50, 6] = 50;	achievements[ach.ach_wave_50, 7] = steam_get_achievement("ach_wave_50");
	achievements[ach.ach_wave_80, 0] = steam_get_stat_int("highest_wave");	achievements[ach.ach_wave_80, 1] = "Wave 80";	achievements[ach.ach_wave_80, 2] = "Beat Wave 80";	achievements[ach.ach_wave_80, 3] = s_ach_wave;	achievements[ach.ach_wave_80, 4] = 10;	achievements[ach.ach_wave_80, 5] = 11;	achievements[ach.ach_wave_80, 6] = 80;	achievements[ach.ach_wave_80, 7] = steam_get_achievement("ach_wave_80");
	achievements[ach.ach_wave_100, 0] = steam_get_stat_int("highest_wave");	achievements[ach.ach_wave_100, 1] = "Wave 100";	achievements[ach.ach_wave_100, 2] = "Beat Wave 100";	achievements[ach.ach_wave_100, 3] = s_ach_wave;	achievements[ach.ach_wave_100, 4] = 12;	achievements[ach.ach_wave_100, 5] = 13;	achievements[ach.ach_wave_100, 6] = 100;	achievements[ach.ach_wave_100, 7] = steam_get_achievement("ach_wave_100");


}